### ISSUE TITLE
4.13.0 release JAR doesn't run

### ISSUE THREAD

**Issue by evergreen-lee-campbell** [IHTSDO/snowstorm#151]
I currently cannot run the compiled release JAR for 4.13.0. I see the following stack trace:

```C:\snowstorm\snowstorm>java -Xms2g -Xmx4g -jar snowstorm-4.13.0.jar --snowstorm.rest-api.readonly=true
Exception in thread "main" java.lang.NoClassDefFoundError: org/snomed/snowstorm/config/Config
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.ClassNotFoundException: org.snomed.snowstorm.config.Config
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 16 more```

Can anyone help?

**Comment by rorydavidson** [comment]
Hi @evergreen-lee-campbell , thanks for pointing that out. I was able to replicate the issue, so I've uploaded a working release JAR now that worked for me.
Please download that again and try?

**Comment by evergreen-lee-campbell** [comment]
Yes, that new JAR does indeed run. Thank you.
