### ISSUE TITLE
Restart SNOWSTORM

### ISSUE THREAD

**Issue by MahboobehJannesari** [IHTSDO/snowstorm#162]
HI, 
I would like to remove all branches and start every thing from the first, How can I do?

I just imported RF2 version snapshot, then I imported RF2 Full version in the same way with import-full, but it give me error and previous version did not work.
should I clear cache or ...?

**Comment by kaicode** [comment]
Hi @MahboobehJannesari,
If you would like to remove all data and start a fresh the command line flag `--delete-indices` can be used. 
See  [loading-snomed / command-line](https://github.com/IHTSDO/snowstorm/blob/master/docs/loading-snomed.md#command-line).
**NOTE: Remember to remove the flag before starting Snowstorm the next time!**

**Comment by MahboobehJannesari** [comment]
Hi, 
ok, 
another question When I start snowstorm as read-only I can not see the Import endpoint,why?

**Comment by kaicode** [comment]
The read-only flag is designed for Public instances where it is not possible to modify the content.
You can either: 
- Start Snowstorm with read-only mode disabled until you have the content imported and then switch to read-only.
- Or run two Snowstorm instances, the first for public use in read-only mode, the second instance behind a firewall in read-write mode, using the same Elasticsearch indices, for content imports. The second instance would only be needed occasionally.

**Comment by MahboobehJannesari** [comment]
I started to load snomed ct for second time with this command
java -Xms4g -Xmx8g -jar snowstorm-4.12.1.jar --delete-indices --import=/home/ubuntu/Snapshot.zip


I got error:


2020-09-28 13:21:57.774  INFO 4281 --- [heManagerDaemon] o.s.s.c.d.s.i.IdentifierCacheManager     : Topping up IdCache(0 - 01) by 2000
2020-09-28 13:21:57.776 ERROR 4281 --- [heManagerDaemon] o.s.s.c.d.s.i.IdentifierCacheManager     : Failed to top-up IdCache(0 - 01) with 2000 identifiers
java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
	at org.apache.http.util.Asserts.check(Asserts.java:46)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.ensureRunning(CloseableHttpAsyncClientBase.java:90)
	at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:123)
	at org.elasticsearch.client.RestClient.performRequestAsync(RestClient.java:344)
	at org.elasticsearch.client.RestClient.performRequestAsync(RestClient.java:326)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:219)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:192)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:428)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:414)
	at org.springframework.data.elasticsearch.rest.ESRestHighLevelClient.performRequestAndParseEntity(ESRestHighLevelClient.java:47)
	at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:355)
	at org.springframework.data.elasticsearch.rest.ElasticsearchRestClient.doExecute(ElasticsearchRestClient.java:214)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:405)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:394)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:46)
	at org.springframework.data.elasticsearch.core.ElasticsearchTemplate.doSearch(ElasticsearchTemplate.java:979)
	at org.springframework.data.elasticsearch.core.ElasticsearchTemplate.queryForPage(ElasticsearchTemplate.java:280)
	at org.springframework.data.elasticsearch.core.ElasticsearchTemplate.queryForPage(ElasticsearchTemplate.java:275)
	at org.springframework.data.elasticsearch.core.ElasticsearchTemplate.queryForList(ElasticsearchTemplate.java:302)
	at org.snomed.snowstorm.core.data.services.identifier.LocalRandomIdentifierSource.findExistingIdentifiersInAnyBranch(LocalRandomIdentifierSource.java:83)
	at org.snomed.snowstorm.core.data.services.identifier.LocalRandomIdentifierSource.reserveIds(LocalRandomIdentifierSource.java:61)
	at org.snomed.snowstorm.core.data.services.identifier.IdentifierCacheManager.topUp(IdentifierCacheManager.java:112)
	at org.snomed.snowstorm.core.data.services.identifier.IdentifierCacheManager.checkTopUpRequired(IdentifierCacheManager.java:95)
	at org.snomed.snowstorm.core.data.services.identifier.IdentifierCacheManager.run(IdentifierCacheManager.java:60)
	at java.lang.Thread.run(Thread.java:748)
2020-09-28 13:21:57.776  INFO 4281 --- [heManagerDaemon] o.s.s.c.d.s.i.IdentifierCacheManager     : Topping up IdCache(0 - 02) by 4000
2020-09-28 13:21:57.779 ERROR 4281 --- [heManagerDaemon] o.s.s.c.d.s.i.IdentifierCacheManager     : Failed to top-up IdCache(0 - 02) with 4000 identifiers
java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
	at org.apache.http.util.Asserts.check(Asserts.java:46)
