### ISSUE TITLE
Verifying if daily builds have been imported.

### ISSUE THREAD

**Issue by Zawaken** [IHTSDO/snowstorm#175]
Hey,

We have an instance of Snowstorm set up with daily builds enabled, but from what I can see, nothing has gotten imported since one hour after the branch was created.

Will the head of the branch be updated even if the files in the directory are the same size since the last update to head.
Or does Snowstorm check the difference between the files, ignore the files if no changes have happened, and import based on if there are any changes.

**Comment by kaicode** [comment]
Snowstorm compares the timestamp in the filename of the daily build zip file with the head timestamp of the branch. This way it only imports if the daily build content is newer than the latest commit on the branch. If you created the branch after creating the daily build it won't run. Simplest way to trigger it is to rename the zip with a date and time matching now.
Cheers.

**Comment by cogliostro** [comment]
Hi, same system, related question. We see the following during snowstorm startup.

2020-10-27 12:09:16.674  INFO 30664 --- [main] o.s.s.d.ScheduledDailyBuildImportService : Daily build import is enabled.

But after that we don't really see any logged attempts to import daily builds. Looking at the code i figure there should at least be a message saying there are no daily builds available or something like that. We are trying to import a local daily build, which are stored in the folder NO/SNOMEDCT-NO under the workingdirectory of snowstorm with the following configuration in local.properties.

`# Logging
logging.level.org.snomed.snowstorm=DEBUG
logging.level.org.springframework=INFO
logging.level.root=INFO
logging.file.path=/var/log/snowstorm
daily-build.delta-import.enabled=true
# 5 minutes in milliseconds
daily-build.delta-import.schedule=300000
daily-build.import.resources.readonly=true
daily-build.import.resources.local.path=NO
daily-build.import.resources.useCloud=false`

Got any idea what we are doing wrong?

**Comment by cogliostro** [comment]
We are also seeing some of these from time to time. Not sure if related.

```
2020-10-27 14:51:46.354  INFO 30664 --- [http-nio-8080-exec-9] o.s.s.rest.config.RestControllerAdvice   : bad request Branch '/MAIN/SNOMEDCT-NO' does not exist.
2020-10-27 14:51:46.355 DEBUG 30664 --- [http-nio-8080-exec-9] o.s.s.rest.config.RestControllerAdvice   : bad request Branch '/MAIN/SNOMEDCT-NO' does not exist.

java.lang.IllegalArgumentException: Branch '/MAIN/SNOMEDCT-NO' does not exist.
        at io.kaicode.elasticvc.api.VersionControlHelper.getBranchOrThrow(VersionControlHelper.java:147)
        at io.kaicode.elasticvc.api.VersionControlHelper.getBranchCriteria(VersionControlHelper.java:42)
        at org.snomed.snowstorm.core.data.services.ConceptService.getBranchCriteria(ConceptService.java:190)
        at org.snomed.snowstorm.core.data.services.ConceptService.doFind(ConceptService.java:178)
        at org.snomed.snowstorm.core.data.services.ConceptService.find(ConceptService.java:121)
        at org.snomed.snowstorm.core.data.services.ConceptService.find(ConceptService.java:117)
```

```
2020-10-27 14:44:43.004  INFO 30664 --- [http-nio-8080-exec-3] o.s.s.rest.config.RestControllerAdvice   : bad request Branch '/browser/MAIN/SNOMEDCT-NO' does not exist.
2020-10-27 14:44:43.004 DEBUG 30664 --- [http-nio-8080-exec-3] o.s.s.rest.config.RestControllerAdvice   : bad request Branch '/browser/MAIN/SNOMEDCT-NO' does not exist.

java.lang.IllegalArgumentException: Branch '/browser/MAIN/SNOMEDCT-NO' does not exist.
        at io.kaicode.elasticvc.api.VersionControlHelper.getBranchOrThrow(VersionControlHelper.java:147)
        at io.kaicode.elasticvc.api.VersionControlHelper.getBranchCriteria(VersionControlHelper.java:42)
        at org.snomed.snowstorm.core.data.services.ConceptService.findConceptMinis(ConceptService.java:198)
        at org.snomed.snowstorm.core.data.services.ConceptService$$FastClassBySpringCGLIB$$aae2a414.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
```

**Comment by danka74** [comment]
HI,
this is the log from us at the SE NRC:

```
2020-10-23 09:02:57.989  INFO 15178 --- [pool-7-thread-1] o.s.s.dailybuild.Dail BuildService       : New daily build 2020-10-23-063137.zip found for SNOMEDCT-SE
2020-10-23 09:02:58.081  INFO 15178 --- [pool-7-thread-1] o.s.s.dailybuild.Dail BuildService       : Latest version found at 1595506793597 on MAIN/SNOMEDCT-SE.
2020-10-23 09:02:58.087  INFO 15178 --- [pool-7-thread-1] o.s.s.dailybuild.Dail BuildService       : 1 commits found on MAIN/SNOMEDCT-SE since latest release.
2020-10-23 09:02:58.087  INFO 15178 --- [pool-7-thread-1] o.s.s.dailybuild.Dail BuildService       : Release commit found, base version 1595504739334 recorded.
2020-10-23 09:02:58.087  INFO 15178 --- [pool-7-thread-1] o.s.s.dailybuild.Dail BuildService       : Commit 1603350261958 does not have a new base (1595504739334) so will be rolled back.
2020-10-23 09:02:58.087  INFO 15178 --- [pool-7-thread-1] o.s.s.dailybuild.Dail BuildService       : 1 branch commits found to roll back on MAIN/SNOMEDCT-SE.
2020-10-23 09:02:59.251  INFO 15178 --- [pool-7-thread-1] o.s.s.dailybuild.Dail BuildService       : start daily build delta import for code system SNOMEDCT-SE
2020-10-23 09:03:20.872  INFO 15178 --- [pool-7-thread-1] o.s.s.dailybuild.Dail BuildService       : Daily build delta import completed for code system SNOMEDCT-SE

```
and the properties file is here
```
daily-build.delta-import.enabled=True
daily-build.import.resources.useCloud=True
daily-build.import.resources.cloud.bucketName=snomed-dailybuild-se
daily-build.import.resources.cloud.path=
```
if this helps.

**Comment by kaicode** [comment]
The properties file will enable the daily build capability for the instance but it must also be enabled on the codesystem with this flag:
```
"dailyBuildAvailable": true,
```
Example: https://browser.ihtsdotools.org/snowstorm/snomed-ct/codesystems/SNOMEDCT-NO

You could switch on debug logging to get a [log entry](https://github.com/IHTSDO/snowstorm/blob/b72edab687285c39df5b76c43527f46b43f173cb/src/main/java/org/snomed/snowstorm/dailybuild/DailyBuildService.java#L182) when the process checks the filesystem for each enabled codesystem.
Using:
```
logging.level.org.snomed.snowstorm.dailybuild=DEBUG
```

**Comment by kaicode** [comment]
The bad requests you are getting on the REST interface look like a web server (Nginx/Apache or other) mapping issue.. it looks likely that the path being proxied is something like: `localhost:8080//MAIN/SNOMEDCT-NO/concepts` rather than `localhost:8080/MAIN/SNOMEDCT-NO/concepts` with a single slash. Try removing the trailing slash from the proxy target?

**Comment by kaicode** [comment]
Any joy @Zawaken ?

**Comment by Zawaken** [comment]
Hey, sorry for such a late answer, we managed to get it working.

`"dailyBuildAvailable": true,` was the thing that was missing from the codesystem.
So now it works, closing this.

Thank you for the help :)
