### ISSUE TITLE
Snowstorm server issue

### ISSUE THREAD

**Issue by kandascan** [IHTSDO/snowstorm#181]
Hello,

I am trying hosts Snowstorm server using the Snowmed documentation from this site: https://github.com/IHTSDO/snowstorm/blob/master/docs/getting-started.md
I have already instlled all dependencies (for Windows), I runned Elasticsearch version 7.7.0 on my local machine,
![image](https://user-images.githubusercontent.com/15519926/99250963-db5dac80-280c-11eb-8deb-f61e5ac6c190.png)
but the problem is when I am trying start Snowstorm using this command: 
![image](https://user-images.githubusercontent.com/15519926/99251005-ea445f00-280c-11eb-8ee1-553b40020ab6.png)
It seems like server wants to start but got some exception and I cannot go to url: http://localhost:8080
![image](https://user-images.githubusercontent.com/15519926/99251109-119b2c00-280d-11eb-85ff-a3d0fb23a523.png)
![image](https://user-images.githubusercontent.com/15519926/99251147-22e43880-280d-11eb-8d13-76951d0993a3.png)
I’ve already check the firewall rules and open ports, all looks fine on my machine, I am fairly sure that the problem is somewhere in 
snowstorm-4.13.0.jar File.

Can someone tell me what I did wrong?
Thanks
Boguslaw

**Comment by rorydavidson** [comment]
Hi @kandascan , it looks as though you are using an older version of Snowstorm which is incompatible with ElasticSearch v7.x.
Please try with the most recent release, https://github.com/IHTSDO/snowstorm/releases, and see if that helps.

**Comment by kandascan** [comment]
Hi @rorydavidson  thanks for your respond, I did like you suggested I downloaded latest version (v5.0.7) but still getting the same issue:

`C:\Users\BB\Desktop\E-portfolio>java -Xms2g -Xmx4g -jar snowstorm-5.0.7.jar --snowstorm.rest-api.readonly=true
         ____                          _
 __/\__ / ___| _ __   _____      _____| |_ ___  _ __ _ __ ___
 \_\/_/ \___ \| '_ \ / _ \ \ /\ / / __| __/ _ \| '__| '_ ` _ \
 /_/\_\  ___) | | | | (_) \ V  V /\__ \ || (_) | |  | | | | | |
   \/   |____/|_| |_|\___/ \_/\_/ |___/\__\___/|_|  |_| |_| |_|
===============================================================
 :: Snowstorm, SNOMED CT Terminology Server :: (v5.0.7)

2020-11-16 13:52:25.613  INFO 22840 --- [           main] o.snomed.snowstorm.SnowstormApplication  : Starting SnowstormApplication v5.0.7 on DESKTOP-6B9PIAF with PID 22840 (C:\Users\BB\Desktop\E-portfolio\snowstorm-5.0.7.jar started by BB in C:\Users\BB\Desktop\E-portfolio)
2020-11-16 13:52:25.618  INFO 22840 --- [           main] o.snomed.snowstorm.SnowstormApplication  : No active profile set, falling back to default profiles: default
2020-11-16 13:52:29.876  INFO 22840 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Elasticsearch repositories in DEFAULT mode.
2020-11-16 13:52:30.044  INFO 22840 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 162ms. Found 21 Elasticsearch repository interfaces.
2020-11-16 13:52:30.542  INFO 22840 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Reactive Elasticsearch repositories in DEFAULT mode.
2020-11-16 13:52:30.570  INFO 22840 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 27ms. Found 0 Reactive Elasticsearch repository interfaces.
2020-11-16 13:52:33.670  INFO 22840 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler@23f5b5dc' of type [org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-11-16 13:52:33.684  INFO 22840 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'permissionEvaluator' of type [org.snomed.snowstorm.config.MethodSecurityConfig$1] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-11-16 13:52:33.685  INFO 22840 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'methodSecurityConfig' of type [org.snomed.snowstorm.config.MethodSecurityConfig$$EnhancerBySpringCGLIB$$73938cb5] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-11-16 13:52:33.691  INFO 22840 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'methodSecurityMetadataSource' of type [org.springframework.security.access.method.DelegatingMethodSecurityMetadataSource] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-11-16 13:52:34.192  INFO 22840 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2020-11-16 13:52:34.214  INFO 22840 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-11-16 13:52:34.215  INFO 22840 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.37]
2020-11-16 13:52:34.641  INFO 22840 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-11-16 13:52:34.642  INFO 22840 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 8807 ms
2020-11-16 13:52:34.942  INFO 22840 --- [           main] ca.uhn.fhir.util.VersionUtil             : HAPI FHIR version 4.2.0 - Rev 8491707942
2020-11-16 13:52:35.566  WARN 22840 --- [           main] o.s.data.convert.CustomConversions       : Registering converter from class org.springframework.data.geo.Point to interface java.util.Map as writing converter although it doesn't convert to a store-supported type! You might want to check your annotation setup at the converter implementation.
2020-11-16 13:52:35.567  WARN 22840 --- [           main] o.s.data.convert.CustomConversions       : Registering converter from interface java.util.Map to class org.springframework.data.geo.Point as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
2020-11-16 13:52:35.568  WARN 22840 --- [           main] o.s.data.convert.CustomConversions       : Registering converter from class org.springframework.data.elasticsearch.core.geo.GeoPoint to interface java.util.Map as writing converter although it doesn't convert to a store-supported type! You might want to check your annotation setup at the converter implementation.
2020-11-16 13:52:35.568  WARN 22840 --- [           main] o.s.data.convert.CustomConversions       : Registering converter from interface java.util.Map to class org.springframework.data.elasticsearch.core.geo.GeoPoint as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
2020-11-16 13:52:35.575  WARN 22840 --- [           main] o.s.data.convert.CustomConversions       : Registering converter from class org.springframework.data.geo.Point to interface java.util.Map as writing converter although it doesn't convert to a store-supported type! You might want to check your annotation setup at the converter implementation.
2020-11-16 13:52:35.576  WARN 22840 --- [           main] o.s.data.convert.CustomConversions       : Registering converter from interface java.util.Map to class org.springframework.data.geo.Point as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
2020-11-16 13:52:35.577  WARN 22840 --- [           main] o.s.data.convert.CustomConversions       : Registering converter from class org.springframework.data.elasticsearch.core.geo.GeoPoint to interface java.util.Map as writing converter although it doesn't convert to a store-supported type! You might want to check your annotation setup at the converter implementation.
2020-11-16 13:52:35.578  WARN 22840 --- [           main] o.s.data.convert.CustomConversions       : Registering converter from interface java.util.Map to class org.springframework.data.elasticsearch.core.geo.GeoPoint as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
2020-11-16 13:52:35.781  INFO 22840 --- [           main] o.s.d.elasticsearch.support.VersionInfo  : Version Spring Data Elasticsearch: 4.0.4
2020-11-16 13:52:35.781  INFO 22840 --- [           main] o.s.d.elasticsearch.support.VersionInfo  : Version Elasticsearch Client in build: 7.6.2
2020-11-16 13:52:35.782  INFO 22840 --- [           main] o.s.d.elasticsearch.support.VersionInfo  : Version Elasticsearch Client used: 7.7.0
2020-11-16 13:52:35.783  WARN 22840 --- [           main] o.s.d.elasticsearch.support.VersionInfo  : Version mismatch in between Elasticsearch Clients build/use: 7.6.2 - 7.7.0
2020-11-16 13:52:35.783  INFO 22840 --- [           main] o.s.d.elasticsearch.support.VersionInfo  : Version Elasticsearch cluster: 7.7.0
2020-11-16 13:52:37.415  INFO 22840 --- [heManagerDaemon] o.s.s.c.d.s.i.IdentifierCacheManager     : Identifier cache manager polling commencing with 10 second period.
2020-11-16 13:52:37.416  INFO 22840 --- [heManagerDaemon] o.s.s.c.d.s.i.IdentifierCacheManager     : Topping up IdCache(0 - 01) by 2000
2020-11-16 13:52:37.598  INFO 22840 --- [heManagerDaemon] o.s.s.c.d.s.i.IdentifierCacheManager     : Top up of IdCache(0 - 01) by 2000 complete
2020-11-16 13:52:37.599  INFO 22840 --- [heManagerDaemon] o.s.s.c.d.s.i.IdentifierCacheManager     : Topping up IdCache(0 - 00) by 1000
2020-11-16 13:52:37.612  INFO 22840 --- [heManagerDaemon] o.s.s.c.d.s.i.IdentifierCacheManager     : Top up of IdCache(0 - 00) by 1000 complete
2020-11-16 13:52:37.613  INFO 22840 --- [heManagerDaemon] o.s.s.c.d.s.i.IdentifierCacheManager     : Topping up IdCache(0 - 02) by 4000
2020-11-16 13:52:37.629  INFO 22840 --- [heManagerDaemon] o.s.s.c.d.s.i.IdentifierCacheManager     : Top up of IdCache(0 - 02) by 4000 complete
2020-11-16 13:52:37.677  INFO 22840 --- [           main] o.s.s.c.d.s.DialectConfigurationService  : Known dialect en-gb - refset: 900000000000508004
2020-11-16 13:52:37.677  INFO 22840 --- [           main] o.s.s.c.d.s.DialectConfigurationService  : Known dialect en-us - refset: 900000000000509007
2020-11-16 13:52:38.058  INFO 22840 --- [           main] o.s.s.c.d.s.DialectConfigurationService  : 2 known dialects configured
2020-11-16 13:52:38.706  INFO 22840 --- [           main] o.s.s.c.d.s.PermissionServiceCache       : Cleared permissions cache.
2020-11-16 13:52:39.948  INFO 22840 --- [           main] o.i.drools.service.TestResourceProvider  : 0 semantic tags loaded
2020-11-16 13:52:39.949  INFO 22840 --- [           main] o.i.drools.service.TestResourceProvider  : 0 case significant words loaded
2020-11-16 13:52:39.952  INFO 22840 --- [           main] o.i.drools.service.TestResourceProvider  : 0 US to GB term map entries loaded
2020-11-16 13:52:40.841  INFO 22840 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Creating filter chain: any request, [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@6ef81f31, org.springframework.security.web.context.SecurityContextPersistenceFilter@10ec523c, org.springframework.security.web.header.HeaderWriterFilter@5f84abe8, org.springframework.security.web.authentication.logout.LogoutFilter@16c3ca31, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@79767781, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@aced190, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@6075b2d3, org.springframework.security.web.session.SessionManagementFilter@30135202, org.springframework.security.web.access.ExceptionTranslationFilter@1ded7b14, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@5ca1f591]
2020-11-16 13:52:41.732  INFO 22840 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Initializing ExecutorService 'taskScheduler'
2020-11-16 13:52:41.784  INFO 22840 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2020-11-16 13:52:41.786  INFO 22840 --- [           main] d.s.w.p.DocumentationPluginsBootstrapper : Context refreshed
2020-11-16 13:52:41.797  INFO 22840 --- [           main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
2020-11-16 13:52:41.819  INFO 22840 --- [           main] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
2020-11-16 13:52:42.203  INFO 22840 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: findConceptsUsingGET_1
2020-11-16 13:52:42.207  INFO 22840 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: findDescriptionsUsingGET_1
2020-11-16 13:52:42.271  INFO 22840 --- [           main] o.snomed.snowstorm.SnowstormApplication  : Started SnowstormApplication in 17.587 seconds (JVM running for 19.052)
2020-11-16 13:52:42.273  INFO 22840 --- [           main] i.k.elasticvc.api.ComponentService       : Initialising indices
2020-11-16 13:52:42.357  INFO 22840 --- [           main] ication$$EnhancerBySpringCGLIB$$fe6de998 : index.max_terms_count is updated to 500000 for semantic
2020-11-16 13:52:42.444  INFO 22840 --- [           main] ication$$EnhancerBySpringCGLIB$$fe6de998 : index.max_terms_count is updated to 500000 for concept
2020-11-16 13:52:42.494  INFO 22840 --- [           main] ication$$EnhancerBySpringCGLIB$$fe6de998 : index.max_terms_count is updated to 500000 for description
2020-11-16 13:52:42.547  INFO 22840 --- [           main] ication$$EnhancerBySpringCGLIB$$fe6de998 : index.max_terms_count is updated to 500000 for relationship
2020-11-16 13:52:42.600  INFO 22840 --- [           main] ication$$EnhancerBySpringCGLIB$$fe6de998 : index.max_terms_count is updated to 500000 for member
2020-11-16 13:52:42.616  INFO 22840 --- [           main] o.s.s.c.data.services.CodeSystemService  : 19 code system configurations available.
CodeSystemConfiguration{name='US', shortName='SNOMEDCT-US', module='731000124108'}
CodeSystemConfiguration{name='Estonia', shortName='SNOMEDCT-EE', module='11000181102'}
CodeSystemConfiguration{name='Netherlands', shortName='SNOMEDCT-NL', module='11000146104'}
CodeSystemConfiguration{name='Spain', shortName='SNOMEDCT-ES', module='449081005'}
CodeSystemConfiguration{name='Denmark', shortName='SNOMEDCT-DK', module='554471000005108'}
CodeSystemConfiguration{name='Ireland', shortName='SNOMEDCT-IE', module='11000220105'}
CodeSystemConfiguration{name='ICD10', shortName='SNOMEDCT-ICD10', module='5991000124107'}
CodeSystemConfiguration{name='Canada English', shortName='SNOMEDCT-CA', module='20621000087109'}
CodeSystemConfiguration{name='New Zealand', shortName='SNOMEDCT-NZ', module='21000210109'}
CodeSystemConfiguration{name='Norway', shortName='SNOMEDCT-NO', module='51000202101'}
CodeSystemConfiguration{name='UK Clinical', shortName='SNOMEDCT-UKC', module='999000021000000109'}
CodeSystemConfiguration{name='Belgium', shortName='SNOMEDCT-BE', module='11000172109'}
CodeSystemConfiguration{name='International', shortName='SNOMEDCT', module='900000000000207008'}
CodeSystemConfiguration{name='Canada French', shortName='SNOMEDCT-CAF', module='20611000087101'}
CodeSystemConfiguration{name='Australia', shortName='SNOMEDCT-AU', module='32506021000036107'}
CodeSystemConfiguration{name='UK', shortName='SNOMEDCT-UK', module='83821000000107'}
CodeSystemConfiguration{name='India', shortName='SNOMEDCT-IN', module='1121000189102'}
CodeSystemConfiguration{name='Uruguay', shortName='SNOMEDCT-UY', module='5631000179106'}
CodeSystemConfiguration{name='Sweden', shortName='SNOMEDCT-SE', module='45991000052106'}
2020-11-16 13:52:42.639  INFO 22840 --- [           main] io.kaicode.elasticvc.api.BranchService   : Creating branch Branch{path=MAIN, base=1605531162632, head=1605531162632, start=1605531162632, end=null}
2020-11-16 13:52:42.733 ERROR 22840 --- [           main] o.snomed.snowstorm.SnowstormApplication  : Branch 'MAIN' does not exist.

java.lang.IllegalArgumentException: Branch 'MAIN' does not exist.
        at io.kaicode.elasticvc.api.VersionControlHelper.getBranchOrThrow(VersionControlHelper.java:147)
        at io.kaicode.elasticvc.api.VersionControlHelper.getBranchCriteria(VersionControlHelper.java:42)
        at org.snomed.snowstorm.core.data.services.ReferenceSetMemberService.findConfiguredReferenceSetTypes(ReferenceSetMemberService.java:368)
        at org.snomed.snowstorm.core.data.services.ReferenceSetMemberService.setupTypes(ReferenceSetMemberService.java:342)
        at org.snomed.snowstorm.core.data.services.ReferenceSetMemberService.init(ReferenceSetMemberService.java:334)
        at org.snomed.snowstorm.SnowstormApplication.run(SnowstormApplication.java:82)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:786)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:776)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
        at org.snomed.snowstorm.SnowstormApplication.main(SnowstormApplication.java:59)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)

2020-11-16 13:52:42.736  INFO 22840 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-11-16 13:52:42.739 ERROR 22840 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute ApplicationRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:789)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:776)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
        at org.snomed.snowstorm.SnowstormApplication.main(SnowstormApplication.java:59)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.IllegalArgumentException: Branch 'MAIN' does not exist.
        at io.kaicode.elasticvc.api.VersionControlHelper.getBranchOrThrow(VersionControlHelper.java:147)
        at io.kaicode.elasticvc.api.VersionControlHelper.getBranchCriteria(VersionControlHelper.java:42)
        at org.snomed.snowstorm.core.data.services.ReferenceSetMemberService.findConfiguredReferenceSetTypes(ReferenceSetMemberService.java:368)
        at org.snomed.snowstorm.core.data.services.ReferenceSetMemberService.setupTypes(ReferenceSetMemberService.java:342)
        at org.snomed.snowstorm.core.data.services.ReferenceSetMemberService.init(ReferenceSetMemberService.java:334)
        at org.snomed.snowstorm.SnowstormApplication.run(SnowstormApplication.java:82)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:786)
        ... 13 common frames omitted

2020-11-16 13:52:43.049  INFO 22840 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
2020-11-16 13:52:43.055  INFO 22840 --- [heManagerDaemon] o.s.s.c.d.s.i.IdentifierCacheManager     : Identifier cache manager sleep interrupted.
2020-11-16 13:52:43.055  INFO 22840 --- [heManagerDaemon] o.s.s.c.d.s.i.IdentifierCacheManager     : Identifier cache manager polling stopped.
2020-11-16 13:52:43.371  INFO 22840 --- [-status-polling] o.s.s.c.d.s.c.ClassificationService      : Classification status polling thread stopped.`

**Comment by rorydavidson** [comment]
@kandascan the data may be corrupted with the first run of the incompatible version.
I would recommend stopping ElasticSearch, and then deleting all the node data on disk (the data is stored in a folder called "data" in the elastic search root directory), and then restarting ElasticSearch, followed by Snowstorm again to recreate again.

**Comment by kandascan** [comment]
@rorydavidson thanks for your advice, after deleting old data Snowstorm started without any issues:
![image](https://user-images.githubusercontent.com/15519926/99256829-48297480-2816-11eb-901a-2ec59187dfe4.png)

**Comment by rorydavidson** [comment]
Great, glad to hear it.
