### ISSUE TITLE
Elasticsearch Timeout issue with Drug Extension import

### ISSUE THREAD

**Issue by steve1973** [IHTSDO/snowstorm#271]
Hi there, I've been trying to do a fresh import of the latest legacy International (Full), UK Clinical (Full) & Drug Extension (Snapshot), but I've been getting an Elasticsearch timeout when importing the Drug Extension. I had this a few months ago, so used the previous version which worked fine. I have no problem with the International or UKC and have also tried bypassing the UKC import in case it's a resources issues, but still experience the same error. I also increased memory & disk space, but still no luck so wondered if you had any ideas? We will be switching over to the new format soon, but ideally just wanted to import the legacy format this time around. Many thanks. (I've tried v6.2.0 & v7.0.1 of Snowstorm)

2021-05-24 15:21:39.925  INFO 1470 --- [pool-2-thread-1] o.s.s.c.d.s.SemanticIndexUpdateService   : Performing incremental update of inferred semantic index
2021-05-24 15:22:10.085 ERROR 1470 --- [pool-2-thread-1] o.s.s.core.rf2.rf2import.ImportService   : Failed RF2 SNAPSHOT import on branch MAIN/SNOMEDCT-DMD. ID b5d57bb5-b96c-4827-9ca6-0477d8145bfc

org.springframework.dao.DataAccessResourceFailureException: 30,000 milliseconds timeout on connection http-outgoing-0 [ACTIVE]; nested exception is java.lang.RuntimeException: 30,000 milliseconds timeout on connection http-outgoing-0 [ACTIVE]
        at org.springframework.data.elasticsearch.core.ElasticsearchExceptionTranslator.translateExceptionIfPossible(ElasticsearchExceptionTranslator.java:76)
        at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.translateException(ElasticsearchRestTemplate.java:398)
        at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.execute(ElasticsearchRestTemplate.java:381)
        at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.searchScrollStart(ElasticsearchRestTemplate.java:304)
        at org.springframework.data.elasticsearch.core.AbstractElasticsearchTemplate.searchForStream(AbstractElasticsearchTemplate.java:266)
        at org.springframework.data.elasticsearch.core.AbstractElasticsearchTemplate.searchForStream(AbstractElasticsearchTemplate.java:253)
        at org.snomed.snowstorm.core.data.services.SemanticIndexUpdateService.buildRelevantPartsOfExistingGraph(SemanticIndexUpdateService.java:576)
        at org.snomed.snowstorm.core.data.services.SemanticIndexUpdateService.updateSemanticIndex(SemanticIndexUpdateService.java:202)
        at org.snomed.snowstorm.core.data.services.SemanticIndexUpdateService.updateStatedAndInferredSemanticIndex(SemanticIndexUpdateService.java:127)
        at org.snomed.snowstorm.core.data.services.SemanticIndexUpdateService.preCommitCompletion(SemanticIndexUpdateService.java:91)
        at io.kaicode.elasticvc.api.BranchService.completeCommit(BranchService.java:398)
        at io.kaicode.elasticvc.domain.Commit.close(Commit.java:61)
        at org.snomed.snowstorm.core.rf2.rf2import.ImportComponentFactoryImpl.completeImportCommit(ImportComponentFactoryImpl.java:217)
        at org.snomed.snowstorm.core.rf2.rf2import.ImportComponentFactoryImpl.loadingComponentsCompleted(ImportComponentFactoryImpl.java:206)
        at org.ihtsdo.otf.snomedboot.ReleaseImporter$ImportRun.doLoadReleaseFiles(ReleaseImporter.java:228)
        at org.ihtsdo.otf.snomedboot.ReleaseImporter$ImportRun.doLoadReleaseFiles(ReleaseImporter.java:180)
        at org.ihtsdo.otf.snomedboot.ReleaseImporter$ImportRun.access$100(ReleaseImporter.java:164)
        at org.ihtsdo.otf.snomedboot.ReleaseImporter.loadSnapshotReleaseFiles(ReleaseImporter.java:44)
        at org.ihtsdo.otf.snomedboot.ReleaseImporter.loadSnapshotReleaseFiles(ReleaseImporter.java:68)
        at org.snomed.snowstorm.core.rf2.rf2import.ImportService.snapshotImport(ImportService.java:207)
        at org.snomed.snowstorm.core.rf2.rf2import.ImportService.importFiles(ImportService.java:158)
        at org.snomed.snowstorm.core.rf2.rf2import.ImportService.importArchive(ImportService.java:109)
        at org.snomed.snowstorm.core.rf2.rf2import.ImportService.lambda$importArchiveAsync$1(ImportService.java:250)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by kaicode** [comment]
Hi @steve1973, sorry to hear you are having trouble importing the UK content.

Regarding the import types, Snowstorm supports importing the RF2 Full (all historic releases) for the content imported into the `MAIN` branch but does not yet have support for importing the RF2 Full on an extension branch. It sounds like you imported the UK Edition RF2 Full on `MAIN` which would be fine.

The timeout you are seeing is happening in the last step of the import during creation of the semantic index for this content. The semantic index includes the transitive closure and other attribute information for every concept to support ECL. We have seen similar errors in the past when saving large sets of components on slower Elasticsearch instances but the stacktrace above shows that the application is loading parts of the existing semantic index during this timeout which is more unusual.

Elasticsearch is quite memory hungry and having not enough memory is usually the thing that slows it down. For the import of this large extension I would suggest ensuring that the server has at least 16G of memory with 8G assigned to the Elasticsearch JVM heap and 6G to the Snowstorm JVM. Snowstorm is unlikely to use that much which will leave plenty of RAM for OS level disk caching that Elasticsearch also uses.

**Comment by steve1973** [comment]
Thanks for the quick response Kai. I did wonder about increasing the memory allocation, so will give that a go. The instance has 16GB, but I've been using the defaults. With regards to the UK Clinical Extension, I've been importing the FULL release on to the MAIN/SNOMEDCT-UKC branch. It seems to be ok, but should I only be importing the SNAPSHOT?

**Comment by kaicode** [comment]
Correct, importing a FULL on any branch other than MAIN will not work correctly. 

When setting up an extension Code System the correct `dependantVersionEffectiveTime` should be set, this makes the extension branch branch-off MAIN at the correct point in time so that the import is based on the correct version of the International Edition. This step of selecting the correct version of the International Edition is a manual step through the API at the moment. It is possible to import each version of an extension in turn, using the Code System "upgrade" function between each one, to build up the history of an extension.. but this would be a very manual process.

It should be possible to automate the selection of the correct International content during an extension FULL import by using the module dependency refset but a feature like this has not yet been developed. The previous versions under the MAIN/SNOMEDCT-UKC branch will be a mix of historic UK content and the latest International content. It would be best to import a Snapshot instead.

**Comment by steve1973** [comment]
Thanks Kai, that's really useful. I tried with the settings you suggested and I think it got a little further, but ultimately failed with the same error. I've copied the error from the ES logs this time. I've also started up a new instance with 32GB of memory and allocated 16GB to ES, so will let you know how that goes.
[2021-05-25T12:50:17,582][WARN ][r.suppressed             ] [ip-172-16-21-219] path: /semantic/_search, params: {typed_keys=true, max_concurrent_shard_requests=5, ignore_unavailable=false, expand_wildcards=open, allow_no_indices=true, ignore_throttled=true, scroll=60000ms, index=semantic, search_type=dfs_query_then_fetch, batched_reduce_size=512, ccs_minimize_roundtrips=true}
org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:551) [elasticsearch-7.9.2.jar:7.9.2]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:309) [elasticsearch-7.9.2.jar:7.9.2]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:582) [elasticsearch-7.9.2.jar:7.9.2]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:393) [elasticsearch-7.9.2.jar:7.9.2]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.access$100(AbstractSearchAsyncAction.java:68) [elasticsearch-7.9.2.jar:7.9.2]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:245) [elasticsearch-7.9.2.jar:7.9.2]
        at org.elasticsearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:73) [elasticsearch-7.9.2.jar:7.9.2]
        at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:59) [elasticsearch-7.9.2.jar:7.9.2]
        at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:403) [elasticsearch-7.9.2.jar:7.9.2]
        at org.elasticsearch.transport.TransportService$6.handleException(TransportService.java:638) [elasticsearch-7.9.2.jar:7.9.2]
        at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1172) [elasticsearch-7.9.2.jar:7.9.2]
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1281) [elasticsearch-7.9.2.jar:7.9.2]
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1255) [elasticsearch-7.9.2.jar:7.9.2]
        at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:61) [elasticsearch-7.9.2.jar:7.9.2]
        at org.elasticsearch.transport.TransportChannel.sendErrorResponse(TransportChannel.java:56) [elasticsearch-7.9.2.jar:7.9.2]
        at org.elasticsearch.action.support.ChannelActionListener.onFailure(ChannelActionListener.java:51) [elasticsearch-7.9.2.jar:7.9.2]
        at org.elasticsearch.search.SearchService.lambda$runAsync$0(SearchService.java:414) [elasticsearch-7.9.2.jar:7.9.2]
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44) [elasticsearch-7.9.2.jar:7.9.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:737) [elasticsearch-7.9.2.jar:7.9.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.9.2.jar:7.9.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: org.elasticsearch.tasks.TaskCancelledException: cancelled
        at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:159) ~[elasticsearch-7.9.2.jar:7.9.2]
        at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:464) ~[elasticsearch-7.9.2.jar:7.9.2]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:444) ~[elasticsearch-7.9.2.jar:7.9.2]
        at org.elasticsearch.search.SearchService.access$200(SearchService.java:136) ~[elasticsearch-7.9.2.jar:7.9.2]
        at org.elasticsearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:396) ~[elasticsearch-7.9.2.jar:7.9.2]
        at org.elasticsearch.search.SearchService.lambda$runAsync$0(SearchService.java:412) ~[elasticsearch-7.9.2.jar:7.9.2]
        ... 6 more

**Comment by rorydavidson** [comment]
Hi @steve1973 I was able to import both the UK clinical edition and drugs extension, even if the latter took a while.  
I ran the `docker-compose.yml` but gave Elasticsearch 8Gb and Snowstorm 6Gb. 

I did the imports in the following order as the UK extension has an unexpected structure:
1. January 2021 International snapshot onto MAIN
2. May 2021 UK clinical edition zip file containing all snapshots in that release package onto MAIN/SNOMEDCT-GB (with create release flag to true)
3. May 2021 UK drug edition snapshot onto MAIN/SNOMEDCT-GB
4. Merge MAIN/SNOMEDCT-GB into MAIN/SNOMEDCT-GB/2021-05-12
5. May 2021 UK drug snapshot onto MAIN/SNOMEDCT-GB (this is the one that took a long time)
6. Merge MAIN/SNOMEDCT-GB into MAIN/SNOMEDCT-GB/2021-05-12

That might help.

**Comment by steve1973** [comment]
Thanks @rorydavidson, I've been doing this through the Swagger UI:

1. January 2021 International FULL onto MAIN
2. Create Codesystem for branchPath SNOMEDCT-UKC, specifying dependant version
3. Import May 2021 UK clinical extension zip on branchPath SNOMEDCT-UKC, createCodeSystem set to true, Snapshot
4. Added config to application.properites (codesystem.config.SNOMEDCT-DMD=Drug Extension|999000011000001104)
5. Create Codesystem for branchPath SNOMEDCT-DMD, specifying dependant version
6. Import May 2021 Drug Extension zip on branchPath SNOMEDCT-DMD, createCodeSystem set to true, Snapshot

I've been following the online docs, so not quite clear on the release flag and merge you mention. The above had been working up until the end of 2020. Also, are your steps for the legacy format or the new data structure?

**Comment by steve1973** [comment]
@rorydavidson & @kaicode I've done a bit more investigation and found that if I import just snapshots as you have done above then it works fine for International, UK & Drug, but if do a full International import and then try to import a snapshot of UK or Drug then I see the error. I had previously been importing full International & full UK, so assumed it was just a problem relating to Drug, but after finding out from @kaicode that full imports are only supported on the main branch I tried to import just the UK snapshot and that failed in the same way. Just to be clear, these are the steps I've been following and I have been using the Swagger UI:

1. Import FULL international 20210131
2. Create code system for SNOMEDCT-UKC, branch MAIN/SNOMEDCT-UKC.
3. Import UK Clinical 20210512 SNAPSHOT onto MAIN/SNOMEDCT-UKC, CreateCodeSystemVersion - true.

Would it be possible for you to test again with the FULL International release please? I presume what I'm doing is correct?

**Comment by steve1973** [comment]
@kaicode @rorydavidson Hi there, I started a fresh with a new Ubuntu 20.04 instance and tried a native install with the necessary components and I also tried using a docker container. Both worked ok for the UKC snapshot when a FULL international has already been imported. I had been using v7.9.2 of ES, so not sure if it's related to that, but this time I specified v7.7.0. Many thanks for your help.

**Comment by kaicode** [comment]
What you were trying sounds okay to me. We are still recommending Elasticsearch 7.7.0 because this is what we use in our test and production environments. We try not to upgrade too frequently because we understand that this can impact the many external Snowstorm installations.
I'm glad it worked in the end!
