### ISSUE TITLE
Error when loading SNAPSHOT of international version of SNOMED-CD

### ISSUE THREAD

**Issue by waydes** [IHTSDO/snowstorm#312]
I am loading a SNAPSHOT into Snowstorm and this error pops up during the process.  Snowstorm concludes and Swagger seems to work ok, but is this a significant problem? 
I am using the following command line program.

java -Xms2g -Xmx4g -jar snowstorm-7.1.2.jar --delete-indices --import=d:\snowstorm\Snomed_test_snapshot.zip --exit > snowstorm.log
The zip file contains all the files within the SNAPSHOT folder. 

2021-08-31 09:54:57.930  INFO 2344 --- [ol-10-thread-10] i.k.elasticvc.api.ComponentService       : Saving batch of 5000 ReferenceSetMembers
2021-08-31 09:54:58.967  INFO 2344 --- [ol-10-thread-10] i.k.elasticvc.api.ComponentService       : Saving batch of 5000 ReferenceSetMembers
2021-08-31 09:54:59.186  INFO 2344 --- [nio-8080-exec-1] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.

java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x000xe20x010x000x000xde0x030x030x850xc4nHh0xe00xc25wX0xf80xf1cq0xdc$0xd40xbc0xc40x920xfeM0x88cH0x89:0x0e+o],0x000x00r0xc000xc0,0xc0(0xc0$0xc00x140xc00x0a0x000xa50x000xa10x000x9f0x00k0x00i0x00h0x0090x0070x0060x000x880x000x860x000x850xc020xc0.0xc0*0xc0&0xc00x0f0xc00x050x000x9d0x00=0x0050x000x840xc0/0xc0+0xc0'0xc0#0xc00x130xc00x090x000xa40x000xa00x000x9e0x00g0x00?0x00>0x0030x0010x0000x00E0x00C0x00B0xc010xc0-0xc0)0xc0%0xc00x0e0xc00x040x000x9c0x00<0x00/0x00A0x000xff0x010x000x00C0x000x0b0x000x040x030x000x010x020x000x0a0x000x0a0x000x080x000x170x000x190x000x180x000x160x00#0x000x000x000x0d0x00]. HTTP method names must be tokens
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:418)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:260)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:835)

2021-08-31 09:55:00.068  INFO 2344 --- [ol-10-thread-10] i.k.elasticvc.api.ComponentService       : Saving batch of 5000 ReferenceSetMembers
2021-08-31 09:55:01.157  INFO 2344 --- [ol-10-thread-10] i.k.elasticvc.api.ComponentService       : Saving batch of 5000 ReferenceSetMembers
2021-08-31 09:55:02.095  INFO 2344 --- [ol-10-thread-10] i.k.elasticvc.api.ComponentService       : Saving batch of 5000 ReferenceSetMembers

**Comment by kaicode** [comment]
I've not see that error before and the stack trace doesn't have any Snowstorm classes in it so I'm not sure how to debug that.

**Comment by kaicode** [comment]
This looks like a generic error where a badly formed HTTP request has come in to Snowstorm and Tomcat has logged it as info. Doesn't look like anything to worry about.

**Comment by kaicode** [comment]
I was able to reproduce the same error using a badly formed curl statement:
```
curl -XGË localhost:8080/version
```

**Comment by waydes** [comment]
However, I was not using curl but the command line.

Wayde Shipman, DVM, MS
Veterinary Medical Databases, President
Veterinary Medical Information Specialist, Virginia Tech
Oaks Veterinary Clinic, League City, Texas

Office - 281-332-9180 (preferred)
Cell - 832-444-5538
[image: ]


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by kaicode** [comment]
The curl command was just an example of how a badly formed HTTP request going to Snowstorm could reproduce the log message you saw. Curl would not have to be the program to send the request.
The message you are seeing is being logged as INFO and is not cause for concern. Thanks for reaching out to check.

**Comment by waydes** [comment]
Thanks!
Wayde Shipman, DVM, MS
Veterinary Medical Databases, President
Veterinary Medical Information Specialist, Virginia Tech
Oaks Veterinary Clinic, League City, Texas

Office - 281-332-9180 (preferred)
Cell - 832-444-5538
[image: ]


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
