### ISSUE TITLE
Snowstorm error: "Classification status polling thread stopped" - Failing to start on Java 17

### ISSUE THREAD

**Issue by lmvwijk** [IHTSDO/snowstorm#399]
I am not able to run Snowstorm correctly. I am using version snowstorm-7.8.0, together with ElasticSearch 7.7.0, executing the following line:
`java -Xms2g -Xmx4g -jar snowstorm-7.8.0.jar`

But I also tried it with:
 
`java -Xms2g -Xmx4g -jar snowstorm-7.8.0.jar --snowstorm.rest-api.readonly=true`

They all end at the same line (see the log underneath), but do not actually exit the program.

I have ElasticSearch running locally on 9200, and I only found out after trying to use Swagger that it did not work:

![image](https://user-images.githubusercontent.com/96246325/167138611-32824651-3301-468d-a700-d487edaf2b0a.png)

```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-05-06 14:40:50.221 ERROR 10364 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'FHIRStructureDefinitionProvider': Unsatisfied dependency expressed through field 'structureDefinitionRepository'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'FHIRStructureDefinitionRepository' defined in org.snomed.snowstorm.fhir.repositories.FHIRStructureDefinitionRepository defined in @EnableElasticsearchRepositories declared on Config: Invocation of init method failed; nested exception is java.lang.reflect.InaccessibleObjectException: Unable to make field private java.lang.String java.util.TimeZone.ID accessible: module java.base does not "opens java.util" to unnamed module @3dd4520b
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1420)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
        at org.snomed.snowstorm.SnowstormApplication.main(SnowstormApplication.java:63)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'FHIRStructureDefinitionRepository' defined in org.snomed.snowstorm.fhir.repositories.FHIRStructureDefinitionRepository defined in @EnableElasticsearchRepositories declared on Config: Invocation of init method failed; nested exception is java.lang.reflect.InaccessibleObjectException: Unable to make field private java.lang.String java.util.TimeZone.ID accessible: module java.base does not "opens java.util" to unnamed module @3dd4520b
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1794)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
        ... 28 common frames omitted
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private java.lang.String java.util.TimeZone.ID accessible: module java.base does not "opens java.util" to unnamed module @3dd4520b
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
        at org.springframework.util.ReflectionUtils.makeAccessible(ReflectionUtils.java:782)
        at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:514)
        at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:705)
        at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:389)
        at java.base/java.util.Collections$SingletonSet.forEach(Collections.java:4905)
        at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.createAndRegisterProperty(AbstractMappingContext.java:562)
        at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:520)
        at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:705)
        at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:389)
        at java.base/java.util.Collections$SingletonSet.forEach(Collections.java:4905)
        at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.createAndRegisterProperty(AbstractMappingContext.java:562)
        at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:520)
        at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:705)
        at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:389)
        at java.base/java.util.Collections$SingletonSet.forEach(Collections.java:4905)
        at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.createAndRegisterProperty(AbstractMappingContext.java:562)
        at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:520)
        at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:705)
        at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:389)
        at java.base/java.util.Collections$SingletonSet.forEach(Collections.java:4905)
        at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.createAndRegisterProperty(AbstractMappingContext.java:562)
        at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:520)
        at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:705)
        at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:389)
        at java.base/java.util.Collections$SingletonSet.forEach(Collections.java:4905)
        at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.createAndRegisterProperty(AbstractMappingContext.java:562)
        at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:520)
        at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:705)
        at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:389)
        at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:263)
        at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:206)
        at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:90)
        at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$4(RepositoryFactoryBeanSupport.java:295)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:295)
        at org.springframework.data.elasticsearch.repository.support.ElasticsearchRepositoryFactoryBean.afterPropertiesSet(ElasticsearchRepositoryFactoryBean.java:69)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1790)
        ... 38 common frames omitted

2022-05-06 14:40:50.637  INFO 10364 --- [-status-polling] o.s.s.c.d.s.c.ClassificationService      : Classification status polling thread stopped.
```

I was not sure if I should use the Maven part or if it was only for Docker users, but when I used it, it also gave an error:
```
The goal you specified requires a project to execute but there is no POM in this directory 
```

Not sure if it has anything to do with it?

I am not sure what is going wrong, but are there suggestions to make it work?

**Comment by kaicode** [comment]
Hi @lmvwijk, sorry to hear that Snowstorm is not behaving as expected for you. The `InaccessibleObjectException` makes me wonder if it's a Java version issue. Could you confirm which version of java you are running Snowstorm on please?

This command works on my machine: `java -version`.

Snowstorm is currently developed and tested against Java 11 which is a long-term support (LTS) version.

**Comment by kaicode** [comment]
My understanding is that Java 17 has tighter security around runtime modification of code, which some of the Snowstorm libraries use.

I don't have a machine with Java 17 to test this but adding these flags just after the `java` part when starting Snowstorm may allow it to to start:
```
java –add-opens java.base/java.util=ALL-UNNAMED
```

That should fix this part of the error you are seeing:
```
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private java.lang.String java.util.TimeZone.ID accessible: module java.base does not "opens java.util" to unnamed module xxxx
```

The other option is to use Java 11 instead.

**Comment by lmvwijk** [comment]
Hi Kai,

Thanks for the help! 

The 
```
java –add-opens java.base/java.util=ALL-UNNAMED
```

did not work unfortunately, but with the use of Java 11 I got it running.

**Comment by kaicode** [comment]
@lmvwijk Thanks for letting us know about the flags. 
I'm glad it's working as expected on Java 11 👍
