### ISSUE TITLE
Using Elastic Search

### ISSUE THREAD

**Issue by johnsonf79** [IHTSDO/snowstorm#420]
Is elasticsearch-8.2.3 certified or tested to run snowstorm-7.8.0.jar ?

I tried getting below errors: -
2022-06-27 12:42:12.177  WARN 7584 --- [           main] o.s.data.convert.CustomConversions       : Registering converter from interface java.util.Map to class org.springframework.data.elasticsearch.core.geo.GeoPoint as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
2022-06-27 12:42:12.317  INFO 7584 --- [           main] o.s.d.elasticsearch.support.VersionInfo  : Version Spring Data Elasticsearch: 4.0.4
2022-06-27 12:42:12.317  INFO 7584 --- [           main] o.s.d.elasticsearch.support.VersionInfo  : Version Elasticsearch Client in build: 7.6.2
2022-06-27 12:42:12.317  INFO 7584 --- [           main] o.s.d.elasticsearch.support.VersionInfo  : Version Elasticsearch Client used: 7.7.0
2022-06-27 12:42:12.317  WARN 7584 --- [           main] o.s.d.elasticsearch.support.VersionInfo  : Version mismatch in between Elasticsearch Clients build/use: 7.6.2 - 7.7.0
2022-06-27 12:42:12.518  WARN 7584 --- [           main] .d.e.r.s.AbstractElasticsearchRepository : Cannot create index: Connection is closed; nested exception is java.lang.RuntimeException: Connection is closed
2022-06-27 12:42:12.599  WARN 7584 --- [           main] .d.e.r.s.AbstractElasticsearchRepository : Cannot create index: Connection is closed; nested exception is java.lang.RuntimeException: Connection is closed
2022-06-27 12:42:12.661  WARN 7584 --- [           main] .d.e.r.s.AbstractElasticsearchRepository : Cannot create index: Connection is closed; nested exception is java.lang.RuntimeException: Connection is closed
2022-06-27 12:42:12.724  WARN 7584 --- [           main] .d.e.r.s.AbstractElasticsearchRepository : Cannot create index: Connection is closed; nested exception is java.lang.RuntimeException: Connection is closed
2022-06-27 12:42:12.755  WARN 7584 --- [           main] .d.e.r.s.AbstractElasticsearchRepository : Cannot create index: Connection is closed; nested exception is java.lang.RuntimeException: Connection is closed
2022-06-27 12:42:12.786  WARN 7584 --- [           main] .d.e.r.s.AbstractElasticsearchRepository : Cannot create index: Connection is closed; nested exception is java.lang.RuntimeException: Connection is closed
2022-06-27 12:42:12.880  WARN 7584 --- [           main] .d.e.r.s.AbstractElasticsearchRepository : Cannot create index: Connection is closed; nested exception is java.lang.RuntimeException: Connection is closed
2022-06-27 12:42:13.564  WARN 7584 --- [           main] .d.e.r.s.AbstractElasticsearchRepository : Cannot create index: Connection is closed; nested exception is java.lang.RuntimeException: Connection is closed
2022-06-27 12:42:13.564  INFO 7584 --- [heManagerDaemon] o.s.s.c.d.s.i.IdentifierCacheManager     : Identifier cache manager polling commencing with 10 second period.
2022-06-27 12:42:13.626  INFO 7584 --- [heManagerDaemon] o.s.s.c.d.s.i.IdentifierCacheManager     : Topping up IdCache(0 - 02) by 4000
2022-06-27 12:42:13.736  WARN 7584 --- [           main] .d.e.r.s.AbstractElasticsearchRepository : Cannot create index: Connection is closed; nested exception is java.lang.RuntimeException: Connection is closed
2022-06-27 12:42:13.876 ERROR 7584 --- [heManagerDaemon] o.s.s.c.d.s.i.IdentifierCacheManager     : Failed to top-up IdCache(0 - 02) with 4000 identifiers

org.springframework.dao.DataAccessResourceFailureException: Connection is closed; nested exception is java.lang.RuntimeException: Connection is closed
        at org.springframework.data.elasticsearch.core.ElasticsearchExceptionTranslator.translateExceptionIfPossible(ElasticsearchExceptionTranslator.java:76)
        at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.translateException(ElasticsearchRestTemplate.java:398)
        at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.execute(ElasticsearchRestTemplate.java:381)
        at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.search(ElasticsearchRestTemplate.java:289)
        at org.springframework.data.elasticsearch.core.AbstractElasticsearchTemplate.search(AbstractElasticsearchTemplate.java:331)
        at org.snomed.snowstorm.core.data.services.identifier.LocalRandomIdentifierSource.findExistingIdentifiersInAnyBranch(LocalRandomIdentifierSource.java:86)
        at org.snomed.snowstorm.core.data.services.identifier.LocalRandomIdentifierSource.reserveIds(LocalRandomIdentifierSource.java:65)
        at org.snomed.snowstorm.core.data.services.identifier.IdentifierCacheManager.topUp(IdentifierCacheManager.java:119)
        at org.snomed.snowstorm.core.data.services.identifier.IdentifierCacheManager.checkTopUpRequired(IdentifierCacheManager.java:102)
        at org.snomed.snowstorm.core.data.services.identifier.IdentifierCacheManager.run(IdentifierCacheManager.java:67)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Connection is closed
        at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.translateException(ElasticsearchRestTemplate.java:396)
        ... 9 common frames omitted

**Comment by kaicode** [comment]
Snowstorm does not yet support Elasticsearch 8. The SNOMED International production instances currently run on Elasticsearch 7.7.0 but all unit and integration tests pass on Elasticsearch 7.10.x. 

We have an internal discussion planned about either upgrading to Elasticsearch 8 or moving to OpenSearch which is based on Elasticsearch 7.10. This move will not take place soon.

**Comment by mp3000mp** [comment]
> We have an internal discussion planned about either upgrading to Elasticsearch 8 or moving to OpenSearch which is based on Elasticsearch 7.10. This move will not take place soon.

Hi, have you reached a decision on this topic ?

And if you decided to support Elasticsearch 8, are you open for a PR ?

**Comment by kaicode** [comment]
For the foreseeable future Snowstorm will stick with Elasticsearch because we believe it gives better performance and tuning opportunities for our use case.

While we are usually open to pull requests creating one for an Elasticsearch 8 upgrade would be difficult to evaluate until we have capacity to properly get into this work and perform the necessary testing so there would be a risk that the PR would become stale for some months. Having said this I think an upgrade PR would still be beneficial and may be useful to others.
