### ISSUE TITLE
getting error while uploading extensions

### ISSUE THREAD

**Issue by gauravvaishnav17** [IHTSDO/snowstorm#432]
Hi,
I was trying to upload Indian extension ( i.e SnomedCT_IndiaDrugExtensionRF2_PRODUCTION_IN1000189_202108061T120000Z ) over top of international edition ( SnomedCT_InternationalRF2_PRODUCTION_20210731T120000Z ) on the branch "MAIN/SNOMEDCT-IN" in v8-beta but i'm getting the bellow error 

response: 
{
  "status": "FAILED",
  "type": "SNAPSHOT",
  "moduleIds": [],
  "branchPath": "MAIN/SNOMEDCT-IN",
  "createCodeSystemVersion": true,
  "internalRelease": false
}

Error: 
```
`2022-08-03 17:59:06.533  INFO 10000 --- [pool-2-thread-4] o.s.s.c.data.services.CodeSystemService  : Creating Code System version - Code System: SNOMEDCT-IN, Version: 2021-08-06, Release Branch: MAIN/SNOMEDCT-IN/2021-08-06
2022-08-03 17:59:06.533  INFO 10000 --- [pool-2-thread-4] o.s.s.c.data.services.CodeSystemService  : Versioning content...
2022-08-03 17:59:06.830  INFO 10000 --- [pool-2-thread-4] io.kaicode.elasticvc.api.BranchService   : Open commit on MAIN/SNOMEDCT-IN at 1659529746830
2022-08-03 17:59:08.642  INFO 10000 --- [pool-2-thread-4] o.snomed.snowstorm.core.util.TimerUtil   : Timer MRCM: Load domains took 0.016 seconds
2022-08-03 17:59:08.658  INFO 10000 --- [pool-2-thread-4] o.snomed.snowstorm.core.util.TimerUtil   : Timer MRCM: Load attribute domains took 0.016 seconds
2022-08-03 17:59:08.658  INFO 10000 --- [pool-2-thread-4] o.snomed.snowstorm.core.util.TimerUtil   : Timer MRCM: Load attribute ranges took 0.0 seconds
2022-08-03 17:59:08.720  INFO 10000 --- [pool-2-thread-4] io.kaicode.elasticvc.api.BranchService   : Rolling back commit on MAIN/SNOMEDCT-IN started at 1659529746830
2022-08-03 17:59:08.720  INFO 10000 --- [pool-2-thread-4] io.kaicode.elasticvc.api.BranchService   : Deleting documents on MAIN/SNOMEDCT-IN started at 1659529746830.
2022-08-03 17:59:08.720  INFO 10000 --- [pool-2-thread-4] io.kaicode.elasticvc.api.BranchService   : Clearing end time for documents on [MAIN/SNOMEDCT-IN] ended at 1659529746830.
2022-08-03 17:59:09.314 ERROR 10000 --- [pool-2-thread-4] o.s.s.core.rf2.rf2import.ImportService   : Failed RF2 SNAPSHOT import on branch MAIN/SNOMEDCT-IN. ID c1c7840a-d123-4cc5-8734-68abdd3014ee

java.lang.NullPointerException: null
        at org.snomed.snowstorm.core.data.services.ModuleDependencyService.findAncestorModules(ModuleDependencyService.java:375)
        at org.snomed.snowstorm.core.data.services.ModuleDependencyService.determineClosestParentFromExistingHierarchy(ModuleDependencyService.java:351)
        at org.snomed.snowstorm.core.data.services.ModuleDependencyService.mapTopLevelExtensionModuleToCore(ModuleDependencyService.java:299)
        at org.snomed.snowstorm.core.data.services.ModuleDependencyService.generateModuleDependencies(ModuleDependencyService.java:195)
        at org.snomed.snowstorm.core.data.services.ReleaseService.createVersion(ReleaseService.java:55)
        at org.snomed.snowstorm.core.data.services.CodeSystemService.createVersion(CodeSystemService.java:238)
        at org.snomed.snowstorm.core.data.services.CodeSystemService.createVersionIfCodeSystemFoundOnPath(CodeSystemService.java:286)
        at org.snomed.snowstorm.core.data.services.CodeSystemService$$FastClassBySpringCGLIB$$7d61f252.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
        at org.snomed.snowstorm.core.data.services.CodeSystemService$$EnhancerBySpringCGLIB$$22b40956.createVersionIfCodeSystemFoundOnPath(<generated>)
        at org.snomed.snowstorm.core.rf2.rf2import.ImportService.importArchive(ImportService.java:115)
        at org.snomed.snowstorm.core.rf2.rf2import.ImportService.lambda$importArchiveAsync$1(ImportService.java:261)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)`
```
Am i missing any step in upload of extension , 
kindly please address the issue
Thanks

**Comment by kaicode** [comment]
Hi @gauravvaishnav17, I don't think you have missed a step. I think this may be a bug in behaviour of the module dependency service. That service attempts to create the module dependency refset automatically but this should only happen in the case of authoring and should not do anything when importing versioned content. I will try to get this fixed ASAP.

**Comment by kaicode** [comment]
@gauravvaishnav17 I've just asked around and apparently this will only happen if there is a problem with the module dependency refset data in the extension being imported. It would be nice if the code identified and reported the issue but it doesn't do that yet.

I would be happy to manually check the module dependency refset if I can get a copy of that extension package.

A workaround to this issue is to import with `"createCodeSystemVersion": false`. No code system version will be created but the content will still be accessible in the FHIR API using the system URI for unversioned content: `http://snomed.info/xsct`. For example in the International Edition, this concept is not yet part of a code system version: https://snowstorm.ihtsdotools.org/fhir/CodeSystem/$lookup?system=http://snomed.info/xsct&code=1237087006

I think this workaround makes changing the import behaviour less urgent.

**Comment by kaicode** [comment]
I've now got a copy of the RF2 package you used, I'll check the module dependency refset, but hopefully you are not blocked and can use the workaround.

**Comment by kaicode** [comment]
The module dependency refset should list all the modules in the package and what modules they depend on. Two lines are missing. If you add the following two lines to the file `Snapshot/Refset/Metadata/der2_ssRefset_ModuleDependencySnapshot_IN1000189_20210806.txt` within the RF2 archive then the import completes correctly, even with `"createCodeSystemVersion": true` in the import config:
```
7921643f-facd-4cee-95ef-9a3168735802	20210806	1	13941000189108	900000000000534007	900000000000012004	20210806	20210731
0e3c8ece-45cf-4ff8-8ab1-8145ddb10ded	20210806	1	13941000189108	900000000000534007	900000000000207008	20210806	20210731
```
The columns must be separated by tabs so if you use this be sure your text editor does not convert the tabs to spaces 😄

**Comment by gauravvaishnav17** [comment]
Thank you @kaicode  for addressing the issue 
I'll take a look on this and see where I can go. 😄
