### ISSUE TITLE
Failed RF2 SNAPSHOT import on branch MAIN/SNOMEDCT-ES

### ISSUE THREAD

**Issue by RaulNan10** [IHTSDO/snowstorm#443]
Hello, we're using Snomed version 7.9.3

We installed the International Version and query it and everything seems to work. We follow instructions at https://github.com/IHTSDO/snowstorm/blob/master/docs/loading-snomed.md via command line for the installation.

After some days testing it, we followed instructions from https://github.com/IHTSDO/snowstorm/blob/master/docs/updating-snomed-and-extensions.md and https://confluence.ihtsdotools.org/pages/viewpage.action?pageId=96808301#Exercise1-4.Loadingthelocaleditionorextension

We downloaded extension files form Spanish Snomed repository (same place we get the International Version file), there are 2 extension files SnomedCT_Extension_Española_SNS.zip (13.4Mb) and SnomedCT_Extension_Española_Medicamentos.zip (9.4Mb), we tried to import the first one (same results with the second one).

So, first of all, we created the code system with this body from the Swagger interface:
{
  "name": "Spanish Extension",
  "shortName": "SNOMEDCT-ES",
  "countryCode": "es",
  "branchPath": "MAIN/SNOMEDCT-DK",
  "dependantVersion": 20220731,
  "defaultLanguageCode": "es"
}

International version date was checked and it was 2022-07-31 from Swagger interface.
After press the "Try out" we get a 201 Response code, and a URL in the response header location http://localhost:8080/codesystems/SNOMEDCT-ES if we browse it, it seems correct. (We don't put the data if you don't ask for it to not lengthen this explanation).

Then in the import from swagger interface we create the import job with this body:
{
  "branchPath": "MAIN/SNOMEDCT-ES",
  "createCodeSystemVersion": true,
  "type": "SNAPSHOT"
}

We get the ok and copy the UUID from the response header location, if we browse to the URL in the location we get a JSON with status WAITING_FOR_FILE.
Everyting seems ok until now.

In Swagger in /imports/{importId}/archive with the correct UUID we select the first spanish extension file, press try-out, and the Snowstorm console shows this Exception:
2022-09-19 09:25:23.498  INFO 1700 --- [pool-3-thread-1] o.s.s.core.rf2.rf2import.ImportService   : Starting RF2 SNAPSHOT import on branch MAIN/SNOMEDCT-ES. ID bc053952-78eb-48f8-9e03-d01eb9afd8ac
2022-09-19 09:25:23.701 ERROR 1700 --- [pool-3-thread-1] o.s.s.core.rf2.rf2import.ImportService   : Failed RF2 SNAPSHOT import on branch MAIN/SNOMEDCT-ES. ID bc053952-78eb-48f8-9e03-d01eb9afd8ac

java.lang.IllegalArgumentException: malformed input off : 76, length : 1
        at java.base/java.lang.StringCoding.throwMalformed(StringCoding.java:698)
        at java.base/java.lang.StringCoding.decodeUTF8_0(StringCoding.java:885)
        at java.base/java.lang.StringCoding.newStringUTF8NoRepl(StringCoding.java:981)
        at java.base/java.lang.System$2.newStringUTF8NoRepl(System.java:2201)
        at java.base/java.util.zip.ZipCoder$UTF8.toString(ZipCoder.java:60)
        at java.base/java.util.zip.ZipCoder.toString(ZipCoder.java:87)
        at java.base/java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:303)
        at java.base/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:125)
        at org.ihtsdo.otf.snomedboot.ReleaseImporter.unzipRelease(ReleaseImporter.java:138)
        at org.ihtsdo.otf.snomedboot.ReleaseImporter.unzipRelease(ReleaseImporter.java:108)
        at org.ihtsdo.otf.snomedboot.ReleaseImporter.loadSnapshotReleaseFiles(ReleaseImporter.java:79)
        at org.snomed.snowstorm.core.rf2.rf2import.ImportService.snapshotImport(ImportService.java:213)
        at org.snomed.snowstorm.core.rf2.rf2import.ImportService.importFiles(ImportService.java:158)
        at org.snomed.snowstorm.core.rf2.rf2import.ImportService.importArchive(ImportService.java:111)
      at org.snomed.snowstorm.core.rf2.rf2import.ImportService.lambda$importArchiveAsync$1(ImportService.java:261)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.nio.charset.MalformedInputException: Input length = 1
        ... 20 common frames omitted

Of course in the URL of the import now the status shows "FAILED".

**Comment by kaicode** [comment]
Hi @RaulNan10, thanks for getting in touch.

When creating the code system make sure to change the branch path from the example `"branchPath": "MAIN/SNOMEDCT-DK",` to the Spanish one `"branchPath": "MAIN/SNOMEDCT-ES",`
When uploading the RF2 the whole zip file should be uploaded at once. Maybe the error in the log is because one of the txt files was uploaded instead of the zip file?

**Comment by RaulNan10** [comment]
Sorry!!!, we made quick cut&paste from the instructions used not from the text used, the branchPath was OK it was MAIN/SNOMEDCT-ES, so it was OK.

The uploaded file is the zip file, here is a screenshot from swagger interface.
![Swagger UI](https://user-images.githubusercontent.com/78374051/191008401-e109ae34-215b-4d43-8ef5-1c5867c0c925.png)

What do you suggest us? We can show you the content from the zip files.
Regards.

**Comment by kaicode** [comment]
My college has indicated that Snowstorm may not support loading the Spanish national extension package because the layout of the package, file naming or contents of the package may not be quite as expected.

Snowstorm expects RF2 packages in a standard format, otherwise loading content may fail.

I would be happy to take a look at the package and make some suggestions if you send me a copy. My email is kke at snomed.org.

**Comment by RaulNan10** [comment]
Okay, I'll send you a copy soon. Thanks!

**Comment by kaicode** [comment]
I received the package thank you. There are multiple circumstances preventing the RF2 from being loaded. The file names in the Documentation folder contain non UTF-8 characters, that trips up the unzip process. I tried deleting those but the concept, description, relationship and other files are not named as expected so they can not be found by the load process.

My college informs me that the Spanish NRC are working on making the package more standard to allow existing tools to load it as expected. It may be worth contacting them for more information.

I would recommend waiting for a later release of the Spanish Edition to load into Snowstorm, because even if the filenames are renamed I am told further improvements being made within the package to ensure it loads as expected. You could load the international Spanish translation for now so that at least you have some Spanish translated content for now.
