### ISSUE TITLE
Error un load snomed in snowstorm

### ISSUE THREAD

**Issue by 25027466** [IHTSDO/snowstorm#471]
HI Guys.
I try load snomed argentinian adition in snowstorm but get me this error:
```
C:\>java -Xms4g -Xmx4g -jar snowstorm/snowstorm7.jar --delete-indices --import=SnomedCT-Argentina.zip
         ____                          _
 __/\__ / ___| _ __   _____      _____| |_ ___  _ __ _ __ ___
 \_\/_/ \___ \| '_ \ / _ \ \ /\ / / __| __/ _ \| '__| '_ ` _ \
 /_/\_\  ___) | | | | (_) \ V  V /\__ \ || (_) | |  | | | | | |
   \/   |____/|_| |_|\___/ \_/\_/ |___/\__\___/|_|  |_| |_| |_|
===============================================================
 :: Snowstorm, SNOMED CT Terminology Server :: (v7.12.0)

2023-01-04 12:04:22.907  INFO 5924 --- [           main] o.snomed.snowstorm.SnowstormApplication  : Starting SnowstormApplication v7.12.0 using Java 11.0.17 on INTRANET with PID 5924 (C:\snowstorm\snowstorm7.jar started by nico.martinez in C:\)
2023-01-04 12:04:22.920  INFO 5924 --- [           main] o.snomed.snowstorm.SnowstormApplication  : No active profile set, falling back to 1 default profile: "default"
2023-01-04 12:04:28.214  INFO 5924 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Elasticsearch repositories in DEFAULT mode.
2023-01-04 12:04:28.693  INFO 5924 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 468 ms. Found 21 Elasticsearch repository interfaces.
2023-01-04 12:04:29.547  INFO 5924 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Reactive Elasticsearch repositories in DEFAULT mode.
2023-01-04 12:04:29.584  INFO 5924 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 36 ms. Found 0 Reactive Elasticsearch repository interfaces.
2023-01-04 12:04:30.244  INFO 5924 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=aa8b96ad-f7ae-34e9-a1eb-ba31e47e0e27
2023-01-04 12:04:32.094  INFO 5924 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'permissionEvaluator' of type [org.snomed.snowstorm.config.MethodSecurityConfig$1] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-01-04 12:04:32.096  INFO 5924 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'methodSecurityConfig' of type [org.snomed.snowstorm.config.MethodSecurityConfig$$EnhancerBySpringCGLIB$$c1054dcc] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-01-04 12:04:32.846  INFO 5924 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2023-01-04 12:04:32.879  INFO 5924 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2023-01-04 12:04:32.880  INFO 5924 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.63]
2023-01-04 12:04:33.055  INFO 5924 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2023-01-04 12:04:33.056  INFO 5924 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 9962 ms
2023-01-04 12:04:33.192  INFO 5924 --- [           main] ca.uhn.fhir.util.VersionUtil             : HAPI FHIR version 4.2.0 - Rev 8491707942
2023-01-04 12:04:33.741  INFO 5924 --- [           main] ication$$EnhancerBySpringCGLIB$$4bdfaaaf : Elasticsearch host: http://localhost:9200
2023-01-04 12:04:33.742  INFO 5924 --- [           main] ication$$EnhancerBySpringCGLIB$$4bdfaaaf : Elasticsearch index prefix:
2023-01-04 12:04:34.168  INFO 5924 --- [           main] o.s.s.config.elasticsearch.IndexConfig   : Index name prefix: ''
2023-01-04 12:04:34.216  WARN 5924 --- [           main] o.s.data.convert.CustomConversions       : Registering converter from class org.springframework.data.geo.Point to interface java.util.Map as writing converter although it doesn't convert to a store-supported type! You might want to check your annotation setup at the converter implementation.
2023-01-04 12:04:34.217  WARN 5924 --- [           main] o.s.data.convert.CustomConversions       : Registering converter from interface java.util.Map to class org.springframework.data.geo.Point as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
2023-01-04 12:04:34.222  WARN 5924 --- [           main] o.s.data.convert.CustomConversions       : Registering converter from class org.springframework.data.elasticsearch.core.geo.GeoPoint to interface java.util.Map as writing converter although it doesn't convert to a store-supported type! You might want to check your annotation setup at the converter implementation.
2023-01-04 12:04:34.223  WARN 5924 --- [           main] o.s.data.convert.CustomConversions       : Registering converter from interface java.util.Map to class org.springframework.data.elasticsearch.core.geo.GeoPoint as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
2023-01-04 12:04:34.235  WARN 5924 --- [           main] o.s.data.convert.CustomConversions       : Registering converter from class org.springframework.data.geo.Point to interface java.util.Map as writing converter although it doesn't convert to a store-supported type! You might want to check your annotation setup at the converter implementation.
2023-01-04 12:04:34.237  WARN 5924 --- [           main] o.s.data.convert.CustomConversions       : Registering converter from interface java.util.Map to class org.springframework.data.geo.Point as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
2023-01-04 12:04:34.238  WARN 5924 --- [           main] o.s.data.convert.CustomConversions       : Registering converter from class org.springframework.data.elasticsearch.core.geo.GeoPoint to interface java.util.Map as writing converter although it doesn't convert to a store-supported type! You might want to check your annotation setup at the converter implementation.
2023-01-04 12:04:34.239  WARN 5924 --- [           main] o.s.data.convert.CustomConversions       : Registering converter from interface java.util.Map to class org.springframework.data.elasticsearch.core.geo.GeoPoint as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
2023-01-04 12:04:34.484  INFO 5924 --- [           main] o.s.d.elasticsearch.support.VersionInfo  : Version Spring Data Elasticsearch: 4.0.4
2023-01-04 12:04:34.485  INFO 5924 --- [           main] o.s.d.elasticsearch.support.VersionInfo  : Version Elasticsearch Client in build: 7.6.2
2023-01-04 12:04:34.488  INFO 5924 --- [           main] o.s.d.elasticsearch.support.VersionInfo  : Version Elasticsearch Client used: 7.7.0
2023-01-04 12:04:34.490  WARN 5924 --- [           main] o.s.d.elasticsearch.support.VersionInfo  : Version mismatch in between Elasticsearch Clients build/use: 7.6.2 - 7.7.0
2023-01-04 12:04:34.491  INFO 5924 --- [           main] o.s.d.elasticsearch.support.VersionInfo  : Version Elasticsearch cluster: 7.7.0
2023-01-04 12:04:36.074  INFO 5924 --- [heManagerDaemon] o.s.s.c.d.s.i.IdentifierCacheManager     : Identifier cache manager polling commencing with 10 second period.
2023-01-04 12:04:36.083  INFO 5924 --- [heManagerDaemon] o.s.s.c.d.s.i.IdentifierCacheManager     : Topping up IdCache(0 - 01) by 2000
2023-01-04 12:04:36.195  INFO 5924 --- [           main] o.s.s.c.d.s.DialectConfigurationService  : Known dialect en-ie - refset: 21000220103
2023-01-04 12:04:36.197  INFO 5924 --- [           main] o.s.s.c.d.s.DialectConfigurationService  : Known dialect en-nhs-clinical - refset: 999001261000000100
2023-01-04 12:04:36.199  INFO 5924 --- [           main] o.s.s.c.d.s.DialectConfigurationService  : Known dialect de - refset: 722130004
2023-01-04 12:04:36.200  INFO 5924 --- [           main] o.s.s.c.d.s.DialectConfigurationService  : Known dialect nb-no - refset: 61000202103
2023-01-04 12:04:36.200  INFO 5924 --- [           main] o.s.s.c.d.s.DialectConfigurationService  : Known dialect en-ca - refset: 19491000087109
2023-01-04 12:04:36.202  INFO 5924 --- [           main] o.s.s.c.d.s.DialectConfigurationService  : Known dialect en-us - refset: 900000000000509007
2023-01-04 12:04:36.202  INFO 5924 --- [           main] o.s.s.c.d.s.DialectConfigurationService  : Known dialect en-int-gmdn - refset: 608771002
2023-01-04 12:04:36.203  INFO 5924 --- [           main] o.s.s.c.d.s.DialectConfigurationService  : Known dialect en-nhs-dmd - refset: 999000671000001103
2023-01-04 12:04:36.204  INFO 5924 --- [           main] o.s.s.c.d.s.DialectConfigurationService  : Known dialect fr - refset: 722131000
2023-01-04 12:04:36.205  INFO 5924 --- [           main] o.s.s.c.d.s.DialectConfigurationService  : Known dialect nl-be - refset: 31000172101
2023-01-04 12:04:36.207  INFO 5924 --- [           main] o.s.s.c.d.s.DialectConfigurationService  : Known dialect nl-nl - refset: 31000146106
2023-01-04 12:04:36.210  INFO 5924 --- [           main] o.s.s.c.d.s.DialectConfigurationService  : Known dialect en-uk-ext - refset: 999001251000000103
2023-01-04 12:04:36.211  INFO 5924 --- [           main] o.s.s.c.d.s.DialectConfigurationService  : Known dialect en-nhs-pharmacy - refset: 999000691000001104
2023-01-04 12:04:36.212  INFO 5924 --- [           main] o.s.s.c.d.s.DialectConfigurationService  : Known dialect en-au - refset: 32570271000036106
2023-01-04 12:04:36.213  INFO 5924 --- [           main] o.s.s.c.d.s.DialectConfigurationService  : Known dialect es-uy - refset: 5641000179103
2023-01-04 12:04:36.214  INFO 5924 --- [           main] o.s.s.c.d.s.DialectConfigurationService  : Known dialect es - refset: 450828004
2023-01-04 12:04:36.215  INFO 5924 --- [           main] o.s.s.c.d.s.DialectConfigurationService  : Known dialect fr-ca - refset: 20581000087109
2023-01-04 12:04:36.216  INFO 5924 --- [           main] o.s.s.c.d.s.DialectConfigurationService  : Known dialect nn-no - refset: 91000202106
2023-01-04 12:04:36.217  INFO 5924 --- [           main] o.s.s.c.d.s.DialectConfigurationService  : Known dialect zh - refset: 722128001
2023-01-04 12:04:36.217  INFO 5924 --- [           main] o.s.s.c.d.s.DialectConfigurationService  : Known dialect en-nz - refset: 271000210107
2023-01-04 12:04:36.218  INFO 5924 --- [           main] o.s.s.c.d.s.DialectConfigurationService  : Known dialect es-ar - refset: 450828004
2023-01-04 12:04:36.219  INFO 5924 --- [           main] o.s.s.c.d.s.DialectConfigurationService  : Known dialect fr-be - refset: 21000172104
2023-01-04 12:04:36.225  INFO 5924 --- [           main] o.s.s.c.d.s.DialectConfigurationService  : Known dialect sv-se - refset: 46011000052107
2023-01-04 12:04:36.226  INFO 5924 --- [           main] o.s.s.c.d.s.DialectConfigurationService  : Known dialect ja - refset: 722129009
2023-01-04 12:04:36.226  INFO 5924 --- [           main] o.s.s.c.d.s.DialectConfigurationService  : Known dialect da-dk - refset: 554461000005103
2023-01-04 12:04:36.227  INFO 5924 --- [           main] o.s.s.c.d.s.DialectConfigurationService  : Known dialect et-ee - refset: 71000181105
2023-01-04 12:04:36.227  INFO 5924 --- [           main] o.s.s.c.d.s.DialectConfigurationService  : Known dialect en-uk-drug - refset: 999000681000001101
2023-01-04 12:04:36.228  INFO 5924 --- [           main] o.s.s.c.d.s.DialectConfigurationService  : Known dialect en-gb - refset: 900000000000508004
2023-01-04 12:04:36.442  INFO 5924 --- [heManagerDaemon] o.s.s.c.d.s.i.IdentifierCacheManager     : Top up of IdCache(0 - 01) by 2000 complete
2023-01-04 12:04:36.443  INFO 5924 --- [heManagerDaemon] o.s.s.c.d.s.i.IdentifierCacheManager     : Topping up IdCache(0 - 02) by 4000
2023-01-04 12:04:36.499  INFO 5924 --- [heManagerDaemon] o.s.s.c.d.s.i.IdentifierCacheManager     : Top up of IdCache(0 - 02) by 4000 complete
2023-01-04 12:04:36.500  INFO 5924 --- [heManagerDaemon] o.s.s.c.d.s.i.IdentifierCacheManager     : Topping up IdCache(0 - 00) by 1000
2023-01-04 12:04:36.526  INFO 5924 --- [heManagerDaemon] o.s.s.c.d.s.i.IdentifierCacheManager     : Top up of IdCache(0 - 00) by 1000 complete
2023-01-04 12:04:37.711  INFO 5924 --- [           main] o.s.s.c.d.s.s.CommitServiceHookClient    : CommitServiceHookClient is muted as service url not configured.
2023-01-04 12:04:38.123  INFO 5924 --- [           main] .RestTemplateClassificationStatusService : Classification statuses will be retrieved via REST.
2023-01-04 12:04:38.469  INFO 5924 --- [           main] .s.s.c.d.s.WebRouterConfigurationService : Fall-back route set for use with unconfigured namespaces
2023-01-04 12:04:38.493  INFO 5924 --- [           main] .s.s.c.d.s.WebRouterConfigurationService : WebRoute fhir application/fhir+json -> /fhir/CodeSystem/$lookup?code={SCTID}&version={VERSION_URI}&property=normalForm configured for namespace: default
2023-01-04 12:04:38.495  INFO 5924 --- [           main] .s.s.c.d.s.WebRouterConfigurationService : WebRoute all application/json -> /browser/{BRANCH}/concepts/{SCTID} configured for namespace: default
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.util.ReflectionUtils (jar:file:/C:/snowstorm/snowstorm7.jar!/BOOT-INF/lib/spring-core-5.3.20.jar!/) to field java.util.TimeZone.ID
WARNING: Please consider reporting this to the maintainers of org.springframework.util.ReflectionUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2023-01-04 12:04:41.568  INFO 5924 --- [           main] o.i.drools.service.TestResourceProvider  : 0 semantic tags loaded
2023-01-04 12:04:41.571  INFO 5924 --- [           main] o.i.drools.service.TestResourceProvider  : 0 case significant words loaded
2023-01-04 12:04:41.572  INFO 5924 --- [           main] o.i.drools.service.TestResourceProvider  : 0 US to GB term map entries loaded
2023-01-04 12:04:42.145  INFO 5924 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will secure any request with [org.springframework.security.web.session.DisableEncodeUrlFilter@5fde1d64, org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@5350ab17, org.springframework.security.web.context.SecurityContextPersistenceFilter@438aaa9f, org.springframework.security.web.header.HeaderWriterFilter@54bb1194, org.springframework.security.web.authentication.logout.LogoutFilter@27261190, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@1752e45c, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@5ed65e4b, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@984de01, org.springframework.security.web.session.SessionManagementFilter@30798137, org.springframework.security.web.access.ExceptionTranslationFilter@45297e7]
2023-01-04 12:04:42.738  INFO 5924 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 1 endpoint(s) beneath base path '/actuator'
2023-01-04 12:04:46.746  INFO 5924 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2023-01-04 12:04:46.880  INFO 5924 --- [           main] o.snomed.snowstorm.SnowstormApplication  : Started SnowstormApplication in 25.43 seconds (JVM running for 27.673)
2023-01-04 12:04:46.916  WARN 5924 --- [           main] o.snomed.snowstorm.SnowstormApplication  : Deleting existing Elasticsearch Indices
2023-01-04 12:04:46.917  INFO 5924 --- [           main] i.k.elasticvc.api.ComponentService       : Initialising indices
2023-01-04 12:04:46.919  INFO 5924 --- [           main] i.k.elasticvc.api.ComponentService       : Deleting indices
2023-01-04 12:04:46.919  INFO 5924 --- [           main] i.k.elasticvc.api.ComponentService       : Deleting index refset
2023-01-04 12:04:47.113  INFO 5924 --- [           main] i.k.elasticvc.api.ComponentService       : Deleting index concept
2023-01-04 12:04:47.266  INFO 5924 --- [           main] i.k.elasticvc.api.ComponentService       : Deleting index description
2023-01-04 12:04:47.412  INFO 5924 --- [           main] i.k.elasticvc.api.ComponentService       : Deleting index member
2023-01-04 12:04:47.849  INFO 5924 --- [           main] i.k.elasticvc.api.ComponentService       : Deleting index branch
2023-01-04 12:04:48.023  INFO 5924 --- [           main] i.k.elasticvc.api.ComponentService       : Deleting index relationship
2023-01-04 12:04:48.171  INFO 5924 --- [           main] i.k.elasticvc.api.ComponentService       : Deleting index semantic
2023-01-04 12:04:48.320  INFO 5924 --- [           main] i.k.elasticvc.api.ComponentService       : Creating index refset
2023-01-04 12:04:48.875  INFO 5924 --- [           main] i.k.elasticvc.api.ComponentService       : Creating index concept
2023-01-04 12:04:49.390  INFO 5924 --- [           main] i.k.elasticvc.api.ComponentService       : Creating index description
2023-01-04 12:04:49.882  INFO 5924 --- [           main] i.k.elasticvc.api.ComponentService       : Creating index member
2023-01-04 12:04:50.389  INFO 5924 --- [           main] i.k.elasticvc.api.ComponentService       : Creating index branch
2023-01-04 12:04:50.889  INFO 5924 --- [           main] i.k.elasticvc.api.ComponentService       : Creating index relationship
2023-01-04 12:04:51.435  INFO 5924 --- [           main] i.k.elasticvc.api.ComponentService       : Creating index semantic
2023-01-04 12:04:51.926  INFO 5924 --- [           main] ication$$EnhancerBySpringCGLIB$$4bdfaaaf : Deleting index codesystem
2023-01-04 12:04:52.098  INFO 5924 --- [           main] ication$$EnhancerBySpringCGLIB$$4bdfaaaf : Creating index codesystem
2023-01-04 12:04:52.579  INFO 5924 --- [           main] ication$$EnhancerBySpringCGLIB$$4bdfaaaf : Deleting index identifiers-for-registration
2023-01-04 12:04:52.821  INFO 5924 --- [           main] ication$$EnhancerBySpringCGLIB$$4bdfaaaf : Creating index identifiers-for-registration
2023-01-04 12:04:53.407  INFO 5924 --- [           main] ication$$EnhancerBySpringCGLIB$$4bdfaaaf : Deleting index codesystem-version
2023-01-04 12:04:53.547  INFO 5924 --- [           main] ication$$EnhancerBySpringCGLIB$$4bdfaaaf : Creating index codesystem-version
2023-01-04 12:04:53.998  INFO 5924 --- [           main] ication$$EnhancerBySpringCGLIB$$4bdfaaaf : Deleting index classification
2023-01-04 12:04:54.148  INFO 5924 --- [           main] ication$$EnhancerBySpringCGLIB$$4bdfaaaf : Creating index classification
2023-01-04 12:04:54.612  INFO 5924 --- [           main] ication$$EnhancerBySpringCGLIB$$4bdfaaaf : Deleting index export-config
2023-01-04 12:04:54.761  INFO 5924 --- [           main] ication$$EnhancerBySpringCGLIB$$4bdfaaaf : Creating index export-config
2023-01-04 12:04:55.281  INFO 5924 --- [           main] ication$$EnhancerBySpringCGLIB$$4bdfaaaf : Deleting index classification-equivalent-concepts
2023-01-04 12:04:55.409  INFO 5924 --- [           main] ication$$EnhancerBySpringCGLIB$$4bdfaaaf : Creating index classification-equivalent-concepts
2023-01-04 12:04:55.887  INFO 5924 --- [           main] ication$$EnhancerBySpringCGLIB$$4bdfaaaf : Deleting index classification-relationship-change
2023-01-04 12:04:56.029  INFO 5924 --- [           main] ication$$EnhancerBySpringCGLIB$$4bdfaaaf : Creating index classification-relationship-change
2023-01-04 12:04:56.674  INFO 5924 --- [           main] ication$$EnhancerBySpringCGLIB$$4bdfaaaf : index.max_terms_count is updated to 500000 for semantic
2023-01-04 12:04:56.836  INFO 5924 --- [           main] ication$$EnhancerBySpringCGLIB$$4bdfaaaf : index.max_terms_count is updated to 500000 for concept
2023-01-04 12:04:57.105  INFO 5924 --- [           main] ication$$EnhancerBySpringCGLIB$$4bdfaaaf : index.max_terms_count is updated to 500000 for description
2023-01-04 12:04:57.299  INFO 5924 --- [           main] ication$$EnhancerBySpringCGLIB$$4bdfaaaf : index.max_terms_count is updated to 500000 for relationship
2023-01-04 12:04:57.472  INFO 5924 --- [           main] ication$$EnhancerBySpringCGLIB$$4bdfaaaf : index.max_terms_count is updated to 500000 for member
2023-01-04 12:04:57.688  INFO 5924 --- [           main] o.s.s.c.data.services.CodeSystemService  : Creating Code System branch 'MAIN'.
2023-01-04 12:04:57.699  INFO 5924 --- [           main] io.kaicode.elasticvc.api.BranchService   : Creating branch Branch{path=MAIN, base=1672844697689, head=1672844697689, start=1672844697689, end=null}
2023-01-04 12:04:57.989  INFO 5924 --- [           main] o.s.s.c.d.s.s.CommitServiceHookClient    : restTemplate == null, pre-commit completion done.
2023-01-04 12:04:58.322  INFO 5924 --- [           main] o.s.s.c.data.services.CodeSystemService  : Code System 'SNOMEDCT' created.
2023-01-04 12:04:58.324  INFO 5924 --- [           main] o.s.s.c.data.services.CodeSystemService  : 20 code system configurations available.
CodeSystemConfiguration{name='Estonian Edition', shortName='SNOMEDCT-EE', module='11000181102', countryCode='ee', owner='Estonia Health and Welfare Information Systems Centre'}
CodeSystemConfiguration{name='Irish Edition', shortName='SNOMEDCT-IE', module='11000220105', countryCode='ie', owner='Department of Health / eHealth Ireland'}
CodeSystemConfiguration{name='Danish Edition', shortName='SNOMEDCT-DK', module='554471000005108', countryCode='dk', owner='Danish Health Data Authority'}
CodeSystemConfiguration{name='Swedish Edition', shortName='SNOMEDCT-SE', module='45991000052106', countryCode='se', owner='The National Board of Health and Welfare'}
CodeSystemConfiguration{name='New Zealand Edition', shortName='SNOMEDCT-NZ', module='21000210109', countryCode='nz', owner='Ministry of Health'}
CodeSystemConfiguration{name='Indian Edition', shortName='SNOMEDCT-IN', module='1121000189102', countryCode='in', owner='eHealth Division, MoH&FW'}
CodeSystemConfiguration{name='Canadian English Edition', shortName='SNOMEDCT-CA', module='20621000087109', countryCode='ca', owner='Canada Health Infoway'}
CodeSystemConfiguration{name='Norwegian Edition', shortName='SNOMEDCT-NO', module='51000202101', countryCode='no', owner='The Norwegian Directorate of eHealth'}
CodeSystemConfiguration{name='Australian Edition', shortName='SNOMEDCT-AU', module='32506021000036107', countryCode='au', owner='Australian Digital Health Agency'}
CodeSystemConfiguration{name='United Kingdom Edition', shortName='SNOMEDCT-UK', module='83821000000107', countryCode='gb', owner='NHS Digital Information Representation Services'}
CodeSystemConfiguration{name='Argentinian Edition', shortName='SNOMEDCT-AR', module='11000221109', countryCode='ar', owner='Argentina Ministry of Health'}
CodeSystemConfiguration{name='ICD10', shortName='SNOMEDCT-ICD10', module='5991000124107', countryCode='null', owner='null'}
CodeSystemConfiguration{name='Canadian French Edition', shortName='SNOMEDCT-CAF', module='20611000087101', countryCode='ca', owner='Canada Health Infoway'}
CodeSystemConfiguration{name='International Edition', shortName='SNOMEDCT', module='900000000000207008', countryCode='', owner='SNOMED International'}
CodeSystemConfiguration{name='United Kingdom Clinical Edition', shortName='SNOMEDCT-UKC', module='999000021000000109', countryCode='gb', owner='NHS Digital Information Representation Services'}
CodeSystemConfiguration{name='Uruguay Edition', shortName='SNOMEDCT-UY', module='5631000179106', countryCode='uy', owner='Centro de Servicios de Salud - NRC'}
CodeSystemConfiguration{name='United States Edition', shortName='SNOMEDCT-US', module='731000124108', countryCode='us', owner='National Library of Medicine'}
CodeSystemConfiguration{name='Belgium', shortName='SNOMEDCT-BE', module='11000172109', countryCode='be', owner='Belgian Federal Public Service Health, Food Chain Safety and Environment'}
CodeSystemConfiguration{name='Spanish Edition', shortName='SNOMEDCT-ES', module='449081005', countryCode='es', owner='SNOMED International'}
CodeSystemConfiguration{name='Netherlands Edition', shortName='SNOMEDCT-NL', module='11000146104', countryCode='nl', owner='National IT Institute for Healthcare in the Netherlands (Nicitz)'}
2023-01-04 12:04:58.487  INFO 5924 --- [           main] o.s.s.c.d.s.ReferenceSetMemberService    : Reference set types are configured against branch: 'MAIN'.
2023-01-04 12:04:58.513  INFO 5924 --- [           main] o.s.s.c.d.s.ReferenceSetMemberService    : Setting up reference set types: [MRCMAttributeRange|723592007, ICD-9-CMEquivalenceComplexMap|447563008, AssociationReference|900000000000521006, MRCMDomain|723589008, OWLExpression|762676003, MRCMAttributeDomain|723604009, AttributeValue|900000000000480006, RefsetDescriptor|900000000000456007, DescriptionType|900000000000538005, Simple|446609009, ModuleDependency|900000000000534007, SimpleMapToSCT|1187636009, ICD-10ExtendedMap|447562003, SimpleMapCorrelationToSCT|1193543008, Language|900000000000506000, MRCMModuleScope|723563008, SimpleMapCorrelationFromSCT|1193542003, SimpleMapFromSCT|900000000000496009, Annotation|900000000000516008]
2023-01-04 12:04:58.915  INFO 5924 --- [           main] io.kaicode.elasticvc.api.BranchService   : Open commit on MAIN at 1672844698915
2023-01-04 12:04:58.922  INFO 5924 --- [           main] i.k.elasticvc.api.ComponentService       : Saving batch of 19 ReferenceSetTypes
2023-01-04 12:04:59.525  INFO 5924 --- [           main] o.s.s.c.d.s.s.CommitServiceHookClient    : restTemplate == null, pre-commit completion done.
2023-01-04 12:04:59.531  INFO 5924 --- [           main] ication$$EnhancerBySpringCGLIB$$4bdfaaaf : Completed commit on MAIN in 0.613 seconds.
2023-01-04 12:04:59.874  INFO 5924 --- [           main] io.kaicode.elasticvc.api.BranchService   : Completed commit on MAIN at 1672844698915
2023-01-04 12:04:59.876  INFO 5924 --- [           main] o.snomed.snowstorm.SnowstormApplication  : --- Snowstorm startup complete ---
2023-01-04 12:04:59.879  INFO 5924 --- [           main] o.snomed.snowstorm.SnowstormApplication  : Warming CodeSystem aggregation cache...
2023-01-04 12:04:59.985  INFO 5924 --- [           main] o.snomed.snowstorm.SnowstormApplication  : Warming CodeSystemVersion dependency cache...
2023-01-04 12:04:59.985  INFO 5924 --- [           main] o.snomed.snowstorm.SnowstormApplication  : Caches are hot.
2023-01-04 12:04:59.992 ERROR 5924 --- [           main] o.snomed.snowstorm.SnowstormApplication  : import file could not be read at C:\\SnomedCT-Argentina.zip

java.lang.IllegalArgumentException: import file could not be read at C:\\SnomedCT-Argentina.zip
        at org.snomed.snowstorm.SnowstormApplication.fileExistsForArgument(SnowstormApplication.java:133)
        at org.snomed.snowstorm.SnowstormApplication.run(SnowstormApplication.java:99)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
        at org.snomed.snowstorm.SnowstormApplication.main(SnowstormApplication.java:61)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)

2023-01-04 12:05:00.001  INFO 5924 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-01-04 12:05:00.062 ERROR 5924 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute ApplicationRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:765)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
        at org.snomed.snowstorm.SnowstormApplication.main(SnowstormApplication.java:61)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: java.lang.IllegalArgumentException: import file could not be read at C:\\SnomedCT-Argentina.zip
        at org.snomed.snowstorm.SnowstormApplication.fileExistsForArgument(SnowstormApplication.java:133)
        at org.snomed.snowstorm.SnowstormApplication.run(SnowstormApplication.java:99)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762)
        ... 13 common frames omitted

2023-01-04 12:05:00.182  INFO 5924 --- [heManagerDaemon] o.s.s.c.d.s.i.IdentifierCacheManager     : Identifier cache manager sleep interrupted.
2023-01-04 12:05:00.183  INFO 5924 --- [heManagerDaemon] o.s.s.c.d.s.i.IdentifierCacheManager     : Identifier cache manager polling stopped.
2023-01-04 12:05:00.425  INFO 5924 --- [-status-polling] o.s.s.c.d.s.c.ClassificationService      : Classification status polling thread stopped.
```
My OS is Windows Server 2019
Java 11
Maven 3
Elasticsearch 7 
Snowstorm 7

Thanks!

**Comment by kaicode** [comment]
Hi there. The important part is ` import file could not be read at C:\SnomedCT-Argentina.zip`. You are starting snowstorm from the root of the C drive and using a relative path to the Snomed zip file. Perhaps the zip file is not in the root of the C drive?

**Comment by 25027466** [comment]
hello kaicode!.
That's right, I checked the path of the zip file, and there was the problem.
Fixed.

Thanks!

**Comment by kaicode** [comment]
Glad you sorted it! Cheers
