### ISSUE TITLE
Unable to Import international edition (Elasticsearch version then disk space problem)

### ISSUE THREAD

**Issue by adarsh-M-agrawal** [IHTSDO/snowstorm#498]
Hello,
I am encountering an error while attempting to import SnomedCT_InternationalRF2_PRODUCTION_20230228T120000Z onto Snowstorm v8.1.0 . Please suggest any resolution

``` 2023-03-29 11:10:24.431  INFO 9380 --- [ool-5-thread-10] i.k.elasticvc.api.ComponentService       : Saving batch of 5000 ReferenceSetMembers
2023-03-29 11:10:25.350  INFO 9380 --- [ool-5-thread-10] i.k.elasticvc.api.ComponentService       : Saving batch of 5000 ReferenceSetMembers
2023-03-29 11:10:26.091  INFO 9380 --- [ool-5-thread-10] o.ihtsdo.otf.snomedboot.ReleaseImporter  : 3106221 reference set members read from der2_cRefset_LanguageSnapshot-en_INT_20230228.txt
2023-03-29 11:10:26.092  INFO 9380 --- [pool-2-thread-1] o.s.s.c.r.r.ImportComponentFactoryImpl   : 0 components of type Concept were not imported from RF2 because a newer version was found.
2023-03-29 11:10:26.092  INFO 9380 --- [pool-2-thread-1] o.s.s.c.r.r.ImportComponentFactoryImpl   : 0 components of type Description were not imported from RF2 because a newer version was found.
2023-03-29 11:10:26.092  INFO 9380 --- [pool-2-thread-1] o.s.s.c.r.r.ImportComponentFactoryImpl   : 0 components of type ReferenceSetMember were not imported from RF2 because a newer version was found.
2023-03-29 11:10:26.092  INFO 9380 --- [pool-2-thread-1] o.s.s.c.r.r.ImportComponentFactoryImpl   : 0 components of type Relationship were not imported from RF2 because a newer version was found.
2023-03-29 11:10:26.386  INFO 9380 --- [pool-2-thread-1] i.k.elasticvc.api.ComponentService       : Saving batch of 3349 ReferenceSetMembers
2023-03-29 11:10:41.335  INFO 9380 --- [pool-2-thread-1] d.s.ConceptDefinitionStatusUpdateService : Checking 381433 concepts.
2023-03-29 11:10:43.640 ERROR 9380 --- [pool-2-thread-1] io.kaicode.elasticvc.api.BranchService   : Commit commitListener threw IllegalStateException, rolling back commit 1680066380166 on branch MAIN

java.lang.IllegalStateException: Failed to update concept definition status.org.springframework.data.elasticsearch.UncategorizedElasticsearchException: Elasticsearch exception [type=x_content_parse_exception, reason=[1:955] [bool] failed to parse field [must]]; nested exception is ElasticsearchStatusException[Elasticsearch exception [type=x_content_parse_exception, reason=[1:955] [bool] failed to parse field [must]]]; nested: ElasticsearchException[Elasticsearch exception [type=parsing_exception, reason=[match_phrase_prefix] query does not support [zero_terms_query]]];
        at org.snomed.snowstorm.core.data.services.ConceptDefinitionStatusUpdateService.preCommitCompletion(ConceptDefinitionStatusUpdateService.java:62)
        at io.kaicode.elasticvc.api.BranchService.completeCommit(BranchService.java:409)
        at io.kaicode.elasticvc.domain.Commit.close(Commit.java:61)
        at org.snomed.snowstorm.core.rf2.rf2import.ImportComponentFactoryImpl.completeImportCommit(ImportComponentFactoryImpl.java:217)
        at org.snomed.snowstorm.core.rf2.rf2import.ImportComponentFactoryImpl.loadingComponentsCompleted(ImportComponentFactoryImpl.java:206)
        at org.ihtsdo.otf.snomedboot.ReleaseImporter$ImportRun.doLoadReleaseFiles(ReleaseImporter.java:250)
        at org.ihtsdo.otf.snomedboot.ReleaseImporter$ImportRun.doLoadReleaseFiles(ReleaseImporter.java:202)
        at org.ihtsdo.otf.snomedboot.ReleaseImporter$ImportRun.access$100(ReleaseImporter.java:186)
        at org.ihtsdo.otf.snomedboot.ReleaseImporter.loadSnapshotReleaseFiles(ReleaseImporter.java:46)
        at org.ihtsdo.otf.snomedboot.ReleaseImporter.loadSnapshotReleaseFiles(ReleaseImporter.java:80)
        at org.snomed.snowstorm.core.rf2.rf2import.ImportService.snapshotImport(ImportService.java:213)
        at org.snomed.snowstorm.core.rf2.rf2import.ImportService.importFiles(ImportService.java:158)
        at org.snomed.snowstorm.core.rf2.rf2import.ImportService.importArchive(ImportService.java:111)
        at org.snomed.snowstorm.core.rf2.rf2import.ImportService.lambda$importArchiveAsync$1(ImportService.java:261)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.springframework.data.elasticsearch.UncategorizedElasticsearchException: Elasticsearch exception [type=x_content_parse_exception, reason=[1:955] [bool] failed to parse field [must]]; nested exception is ElasticsearchStatusException[Elasticsearch exception [type=x_content_parse_exception, reason=[1:955] [bool] failed to parse field [must]]]; nested: ElasticsearchException[Elasticsearch exception [type=parsing_exception, reason=[match_phrase_prefix] query does not support [zero_terms_query]]]; ```

**Comment by kaicode** [comment]
What version of Elasticsearch are you using please?

**Comment by adarsh-M-agrawal** [comment]
I am using elasticsearch-v7.7.0

**Comment by kaicode** [comment]
The [8.1.0 release page](https://github.com/IHTSDO/snowstorm/releases/tag/8.1.0) has now been updated to include this breaking change.
@adarsh-M-agrawal Thank you for letting us know that you hit this issue so that we could improve the release notes!

**Comment by adarsh-M-agrawal** [comment]
I also tried with 7.10.0 but getting this error


``` 2023-03-29 16:24:32.891  WARN 3776 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'permissionService': Invocation of init method failed; nested exception is org.springframework.data.elasticsearch.BulkFailureException: Bulk operation has failures. Use ElasticsearchException.getFailedDocuments() for detailed messages [{global-ADMIN=ElasticsearchException[Elasticsearch exception [type=cluster_block_exception, reason=index [admin-permission] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];]]}]
2023-03-29 16:24:32.898  INFO 3776 --- [heManagerDaemon] o.s.s.c.d.s.i.IdentifierCacheManager     : Identifier cache manager sleep interrupted.
2023-03-29 16:24:32.899  INFO 3776 --- [heManagerDaemon] o.s.s.c.d.s.i.IdentifierCacheManager     : Identifier cache manager polling stopped.
2023-03-29 16:24:32.929  INFO 3776 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2023-03-29 16:24:32.957  INFO 3776 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-03-29 16:24:32.997 ERROR 3776 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'permissionService': Invocation of init method failed; nested exception is org.springframework.data.elasticsearch.BulkFailureException: Bulk operation has failures. Use ElasticsearchException.getFailedDocuments() for detailed messages [{global-ADMIN=ElasticsearchException[Elasticsearch exception [type=cluster_block_exception, reason=index [admin-permission] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];]]}]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
        at org.snomed.snowstorm.SnowstormApplication.main(SnowstormApplication.java:61)
        at java. Base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ```

**Comment by kaicode** [comment]
This Elasticsearch error comes when there is not enough disk space. The informative part of the error is `disk usage exceeded flood-stage watermark`. 

Please refer to [Elasticsearch documentation on this](https://www.elastic.co/guide/en/elasticsearch/reference/master/fix-watermark-errors.html) or search the internet for "elasticsearch disk usage exceeded flood-stage watermark".

**Comment by adarsh-M-agrawal** [comment]
I missed that part, its working now thank you for responding

**Comment by kaicode** [comment]
Great news, I'm glad it's working for you. Thanks for confirming 👍
