### ISSUE TITLE
8.3.0 install on Ubuntu has startup warning

### ISSUE THREAD

**Issue by abelardy** [IHTSDO/snowstorm#544]
Always fails early in initialisation

023-08-17 17:10:19.236  INFO 3009 --- [           main] o.snomed.snowstorm.SnowstormApplication  : Starting SnowstormApplication using Java 17.0.8 on iresuser-VirtualBox with PID 3009 (/usr/bin/snowstorm/snowstorm-8.3.0.jar started by root in /usr/bin/snowstorm)
2023-08-17 17:10:19.240  INFO 3009 --- [           main] o.snomed.snowstorm.SnowstormApplication  : No active profile set, falling back to 1 default profile: "default"
2023-08-17 17:10:21.306  INFO 3009 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
2023-08-17 17:10:21.308  INFO 3009 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Elasticsearch repositories in DEFAULT mode.
2023-08-17 17:10:21.532  INFO 3009 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 219 ms. Found 26 Elasticsearch repository interfaces.
2023-08-17 17:10:22.001  INFO 3009 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
2023-08-17 17:10:22.002  INFO 3009 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Reactive Elasticsearch repositories in DEFAULT mode.
2023-08-17 17:10:22.011  INFO 3009 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 8 ms. Found 0 Reactive Elasticsearch repository interfaces.
2023-08-17 17:10:30.825  WARN 3009 --- [           main] com.amazonaws.util.EC2MetadataUtils      : Unable to retrieve the requested metadata (/latest/meta-data/instance-id). Failed to connect to service endpoint:

om.amazonaws.SdkClientException: Failed to connect to service endpoint: 
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:112)
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:70)
	at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.readResource(InstanceMetadataServiceResourceFetcher.java:75)
	at com.amazonaws.internal.EC2ResourceFetcher.readResource(EC2ResourceFetcher.java:66)
etc.

**Comment by kaicode** [comment]
This exception is related to AWS monitoring. It's logged as a warning and does not prevent Snowstorm from starting normally. It is annoying so we could try to switch it off in the default configuration.

**Comment by kaicode** [comment]
@abelardy does your installation complete startup after this?

**Comment by kaicode** [comment]
The log message can be suppressed by increasing the logging level to error for that class by adding this to a local application.properties file:
```
logging.level.com.amazonaws.util.EC2MetadataUtils=ERROR
```
We will look into better ways to disable this in the default installation.

**Comment by abelardy** [comment]
> @abelardy does your installation complete startup after this?

Nope. 

It continues running after the non-fatal AWS monitoring call, but collapses terminally in a heap a little later.
Attempting to load the Jan 2023 IE release only.
WIll retry in a bit to confirm and post error if confirmed

**Comment by kaicode** [comment]
I believe this WARN logging will not be the cause of your issue. Yes, please do share any subsequent errors that are logged just before the failure. 👍
