### ISSUE TITLE
Import failure org.springframework.dao.DataAccessResourceFailureException: 30,000 milliseconds timeout on connection http-outgoing-1 

### ISSUE THREAD

**Issue by tkenda** [IHTSDO/snowstorm#565]
Hello,

We tried several times to upload the SnomedCT_Argentina-EditionRelease_PRODUCTION_20230531T120000Z repository without success.

We have an Ubuntu 22.04LTS VM with 8 cores, 16 GB RAM and more than 120 GB running docker. To deploy we use the docker stack. 

Before deploy we run `sudo sysctl -w vm.max_map_count=262144`, step by step following the docker instructions. 

Because of the timeout error, firstly I suppose that the issue is related to batch size. So we also test using the `--elasticvc.save.batch-size=1000` configuration.

```
snowstorm:
    image: snomedinternational/snowstorm:latest
    container_name: snowstorm
    restart: always
    depends_on:
      elasticsearch:
        condition: service_healthy
    entrypoint: java -Xms2g -Xmx4g --add-opens java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED -cp @/app/jib-classpath-file org.snomed.snowstorm.SnowstormApplication --elasticsearch.urls=http://es:9200 --elasticvc.save.batch-size=1000
    networks:
      elastic:
        aliases:
         - snowstorm
    ports:
      - 8080:8080
```

The issue persist and I have no more clues how to continue. Could you give me a hint?

Thanks!

```
2023-11-02 14:34:51.991  INFO 1 --- [pool-2-thread-1] i.k.elasticvc.api.ComponentService       : Saving batch of 1000 QueryConcepts
2023-11-02 14:34:52.298  INFO 1 --- [pool-2-thread-1] i.k.elasticvc.api.ComponentService       : Saving batch of 1000 QueryConcepts
2023-11-02 14:34:52.602  INFO 1 --- [pool-2-thread-1] i.k.elasticvc.api.ComponentService       : Saving batch of 1000 QueryConcepts
2023-11-02 14:34:52.892  INFO 1 --- [pool-2-thread-1] i.k.elasticvc.api.ComponentService       : Saving batch of 1000 QueryConcepts
2023-11-02 14:34:53.146  INFO 1 --- [pool-2-thread-1] i.k.elasticvc.api.ComponentService       : Saving batch of 1000 QueryConcepts
2023-11-02 14:34:53.467  INFO 1 --- [pool-2-thread-1] i.k.elasticvc.api.ComponentService       : Saving batch of 1000 QueryConcepts
2023-11-02 14:34:53.793  INFO 1 --- [pool-2-thread-1] i.k.elasticvc.api.ComponentService       : Saving batch of 1000 QueryConcepts
2023-11-02 14:34:54.125  INFO 1 --- [pool-2-thread-1] i.k.elasticvc.api.ComponentService       : Saving batch of 1000 QueryConcepts
2023-11-02 14:34:54.427  INFO 1 --- [pool-2-thread-1] i.k.elasticvc.api.ComponentService       : Saving batch of 165 QueryConcepts
2023-11-02 14:34:54.530  INFO 1 --- [pool-2-thread-1] o.snomed.snowstorm.core.util.TimerUtil   : Timer TC index stated: Save updated QueryConcepts took 140.876 seconds
2023-11-02 14:34:54.530  INFO 1 --- [pool-2-thread-1] o.snomed.snowstorm.core.util.TimerUtil   : Timer TC index stated: total took 701.05 seconds
2023-11-02 14:38:04.141  INFO 1 --- [pool-2-thread-1] o.snomed.snowstorm.core.util.TimerUtil   : Timer TC index inferred: Collect changed is-a relationships. took 189.603 seconds
2023-11-02 14:38:18.530  INFO 1 --- [pool-2-thread-1] o.s.s.c.d.s.SemanticIndexUpdateService   : Performing incremental update of inferred semantic index
2023-11-02 14:38:23.780  INFO 1 --- [pool-2-thread-1] o.snomed.snowstorm.core.util.TimerUtil   : Timer TC index inferred: Collect existingAncestors from QueryConcept. took 19.639 seconds
2023-11-02 14:38:30.604  INFO 1 --- [pool-2-thread-1] o.snomed.snowstorm.core.util.TimerUtil   : Timer TC index inferred: Collect existingDescendants from QueryConcept. took 6.824 seconds
2023-11-02 14:38:35.049  INFO 1 --- [pool-2-thread-1] o.snomed.snowstorm.core.util.TimerUtil   : Timer TC index inferred: Build existing graph from nodes. 0 alternative ancestors found. took 4.445 seconds
2023-11-02 14:38:35.049  INFO 1 --- [pool-2-thread-1] o.s.s.c.d.s.SemanticIndexUpdateService   : 0 existing nodes loaded.
2023-11-02 14:38:35.266  INFO 1 --- [pool-2-thread-1] o.snomed.snowstorm.core.util.TimerUtil   : Timer MRCM: Load domains took 0.051 seconds
2023-11-02 14:38:35.313  INFO 1 --- [pool-2-thread-1] o.snomed.snowstorm.core.util.TimerUtil   : Timer MRCM: Load attribute domains took 0.047 seconds
2023-11-02 14:38:35.362  INFO 1 --- [pool-2-thread-1] o.snomed.snowstorm.core.util.TimerUtil   : Timer MRCM: Load attribute ranges took 0.049 seconds
2023-11-02 14:39:38.430 ERROR 1 --- [pool-2-thread-1] o.s.s.core.rf2.rf2import.ImportService   : Failed RF2 SNAPSHOT import on branch MAIN/SNOMEDCT-ES. ID 86725920-b10c-4e58-b30d-91d025876ed4
org.springframework.dao.DataAccessResourceFailureException: 30,000 milliseconds timeout on connection http-outgoing-1 [ACTIVE]; nested exception is java.lang.RuntimeException: 30,000 milliseconds timeout on connection http-outgoing-1 [ACTIVE]
	at org.springframework.data.elasticsearch.core.ElasticsearchExceptionTranslator.translateExceptionIfPossible(ElasticsearchExceptionTranslator.java:75)
	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.translateException(ElasticsearchRestTemplate.java:367)
	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.execute(ElasticsearchRestTemplate.java:350)
	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.searchScrollContinue(ElasticsearchRestTemplate.java:290)
	at org.springframework.data.elasticsearch.core.AbstractElasticsearchTemplate.lambda$searchForStream$2(AbstractElasticsearchTemplate.java:340)
	at org.springframework.data.elasticsearch.core.StreamQueries$1.hasNext(StreamQueries.java:104)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
	at org.snomed.snowstorm.core.data.services.SemanticIndexUpdateService.updateSemanticIndex(SemanticIndexUpdateService.java:261)
	at org.snomed.snowstorm.core.data.services.SemanticIndexUpdateService.updateStatedAndInferredSemanticIndex(SemanticIndexUpdateService.java:127)
	at org.snomed.snowstorm.core.data.services.SemanticIndexUpdateService.preCommitCompletion(SemanticIndexUpdateService.java:91)
	at io.kaicode.elasticvc.api.BranchService.completeCommit(BranchService.java:409)
	at io.kaicode.elasticvc.domain.Commit.close(Commit.java:61)
	at org.snomed.snowstorm.core.rf2.rf2import.ImportComponentFactoryImpl.completeImportCommit(ImportComponentFactoryImpl.java:228)
	at org.snomed.snowstorm.core.rf2.rf2import.ImportComponentFactoryImpl.loadingComponentsCompleted(ImportComponentFactoryImpl.java:217)
	at org.ihtsdo.otf.snomedboot.ReleaseImporter$ImportRun.doLoadReleaseFiles(ReleaseImporter.java:251)
	at org.ihtsdo.otf.snomedboot.ReleaseImporter$ImportRun.doLoadReleaseFiles(ReleaseImporter.java:203)
	at org.ihtsdo.otf.snomedboot.ReleaseImporter.loadSnapshotReleaseFiles(ReleaseImporter.java:46)
	at org.ihtsdo.otf.snomedboot.ReleaseImporter.loadSnapshotReleaseFiles(ReleaseImporter.java:80)
	at org.snomed.snowstorm.core.rf2.rf2import.ImportService.snapshotImport(ImportService.java:221)
	at org.snomed.snowstorm.core.rf2.rf2import.ImportService.importFiles(ImportService.java:168)
	at org.snomed.snowstorm.core.rf2.rf2import.ImportService.importArchive(ImportService.java:121)
	at org.snomed.snowstorm.core.rf2.rf2import.ImportService.lambda$importArchiveAsync$1(ImportService.java:269)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.RuntimeException: 30,000 milliseconds timeout on connection http-outgoing-1 [ACTIVE]
	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.translateException(ElasticsearchRestTemplate.java:365)
	... 25 common frames omitted
Caused by: java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-1 [ACTIVE]
	at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:864)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:283)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1632)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1602)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1572)
	at org.elasticsearch.client.RestHighLevelClient.scroll(RestHighLevelClient.java:1197)
	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.lambda$searchScrollContinue$12(ElasticsearchRestTemplate.java:290)
	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.execute(ElasticsearchRestTemplate.java:348)
	... 24 common frames omitted
Caused by: java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-1 [ACTIVE]
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsyncRequestExecutor.java:387)
	at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:98)
	at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:40)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.timeout(AbstractIODispatch.java:175)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionTimedOut(BaseIOReactor.java:261)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.timeoutCheck(AbstractIOReactor.java:506)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:211)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
	... 1 common frames omitted
```

**Comment by kaicode** [comment]
Hi. I'm sorry getting your Snowstorm instance set up is not going smoothly.
Thank you for the stack trace - the [line of code that is failing](https://github.com/IHTSDO/snowstorm/blob/8.3.0/src/main/java/org/snomed/snowstorm/core/data/services/SemanticIndexUpdateService.java#L261) is actually reading from Elasticsearch. 
How much memory does Elasticsearch have? Also do you have any idea of the speed of the disk you are using?

**Comment by tkenda** [comment]
We are working with a Proxmox enviroment. The issue was not the available memory nor the speed of the disk. We change the VM processor to a more advanced than the default kvm64 and update Ubuntu. The setup works smoothly. Thanks for your rapid response!

**Comment by tkenda** [comment]
I close the issue.
