### ISSUE TITLE
Elasticsearch problem in Docker

### ISSUE THREAD

**Issue by divinebanana** [IHTSDO/snowstorm#579]
Hello there! 

## Summary
When working with `snowstorm`, we encountered a recurring error with running the service locally. The `elasticsearch` container exits with errors in seemingly random moments, forcing the `snowstorm` container to blow up 🔥.

## Setup
- Snowstorm repository with tag `9.2.0`,
- MacBook M2 Pro 16" | 32 GB | Sonoma 14.2.1
- Docker Desktop v4.26.1
- Docker Compose v2.23.3-desktop.2

## Steps to reproduce
1. Download snowstorm repository with tag `9.2.0`
2. Run docker with snowstorm `docker compose up`
3. Load latest International Edition release snapshot
4. Wait for 🔥.

## Steps taken

For MacOS we run the following command for Docker to tackle `max virtual memory areas` error:
```
docker run --rm -ti --privileged centos sysctl vm.max_map_count=262144
```

Additionally pruning docker worked for short term, but is unusable for day to day `snowstorm` usage:
```
docker system prune
```

## Detailed exception

```
elasticsearch exited with code 137
snowstorm      | 2024-01-23 10:22:34.067  INFO 1 --- [pool-2-thread-1] o.s.s.c.d.s.SemanticIndexUpdateService   : Semantic index change summary for stated form: 440454 concepts loaded into the graph. 363980 semantic concepts created including QueryConcept{conceptIdForm=225462008_s, parents=[365484008], ancestors=[365484008, 365441007, 36456004, 138875005, 404684003], stated=true, attrMap=}. No semantic concepts need updating. No semantic concepts need deleting.
snowstorm      | 2024-01-23 10:22:34.070  INFO 1 --- [pool-2-thread-1] i.k.elasticvc.api.ComponentService       : Saving batch of 5000 QueryConcepts
snowstorm      | 2024-01-23 10:22:34.098 ERROR 1 --- [pool-2-thread-1] o.s.s.core.rf2.rf2import.ImportService   : Failed RF2 SNAPSHOT import on branch MAIN. ID d687254b-2113-4e33-bfb8-d0fc2987f000
snowstorm      | 
snowstorm      | org.springframework.dao.DataAccessResourceFailureException: es: No address associated with hostname; nested exception is java.lang.RuntimeException: es: No address associated with hostname
snowstorm      | 	at org.springframework.data.elasticsearch.core.ElasticsearchExceptionTranslator.translateExceptionIfPossible(ElasticsearchExceptionTranslator.java:75)
snowstorm      | 	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.translateException(ElasticsearchRestTemplate.java:367)
snowstorm      | 	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.execute(ElasticsearchRestTemplate.java:350)
snowstorm      | 	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.searchScrollStart(ElasticsearchRestTemplate.java:276)
snowstorm      | 	at org.springframework.data.elasticsearch.core.AbstractElasticsearchTemplate.searchForStream(AbstractElasticsearchTemplate.java:339)
snowstorm      | 	at org.springframework.data.elasticsearch.core.AbstractElasticsearchTemplate.searchForStream(AbstractElasticsearchTemplate.java:326)
snowstorm      | 	at io.kaicode.elasticvc.api.VersionControlHelper.endOldVersionsOnThisBranch(VersionControlHelper.java:358)
snowstorm      | 	at io.kaicode.elasticvc.api.VersionControlHelper.endOldVersions(VersionControlHelper.java:298)
snowstorm      | 	at io.kaicode.elasticvc.api.ComponentService.doSaveBatchComponents(ComponentService.java:79)
snowstorm      | 	at org.snomed.snowstorm.core.data.services.SemanticIndexUpdateService.doSaveBatch(SemanticIndexUpdateService.java:723)
snowstorm      | 	at org.snomed.snowstorm.core.data.services.SemanticIndexUpdateService.updateSemanticIndex(SemanticIndexUpdateService.java:417)
snowstorm      | 	at org.snomed.snowstorm.core.data.services.SemanticIndexUpdateService.updateStatedAndInferredSemanticIndex(SemanticIndexUpdateService.java:126)
snowstorm      | 	at org.snomed.snowstorm.core.data.services.SemanticIndexUpdateService.preCommitCompletion(SemanticIndexUpdateService.java:91)
snowstorm      | 	at io.kaicode.elasticvc.api.BranchService.completeCommit(BranchService.java:409)
snowstorm      | 	at io.kaicode.elasticvc.domain.Commit.close(Commit.java:61)
snowstorm      | 	at org.snomed.snowstorm.core.rf2.rf2import.ImportComponentFactoryImpl.completeImportCommit(ImportComponentFactoryImpl.java:229)
snowstorm      | 	at org.snomed.snowstorm.core.rf2.rf2import.ImportComponentFactoryImpl.loadingComponentsCompleted(ImportComponentFactoryImpl.java:218)
snowstorm      | 	at org.ihtsdo.otf.snomedboot.ReleaseImporter$ImportRun.doLoadReleaseFiles(ReleaseImporter.java:251)
snowstorm      | 	at org.ihtsdo.otf.snomedboot.ReleaseImporter$ImportRun.doLoadReleaseFiles(ReleaseImporter.java:203)
snowstorm      | 	at org.ihtsdo.otf.snomedboot.ReleaseImporter$ImportRun.access$100(ReleaseImporter.java:186)
snowstorm      | 	at org.ihtsdo.otf.snomedboot.ReleaseImporter.loadSnapshotReleaseFiles(ReleaseImporter.java:46)
snowstorm      | 	at org.ihtsdo.otf.snomedboot.ReleaseImporter.loadSnapshotReleaseFiles(ReleaseImporter.java:80)
snowstorm      | 	at org.snomed.snowstorm.core.rf2.rf2import.ImportService.snapshotImport(ImportService.java:216)
snowstorm      | 	at org.snomed.snowstorm.core.rf2.rf2import.ImportService.importFiles(ImportService.java:161)
snowstorm      | 	at org.snomed.snowstorm.core.rf2.rf2import.ImportService.importArchive(ImportService.java:114)
snowstorm      | 	at org.snomed.snowstorm.core.rf2.rf2import.ImportService.lambda$importArchiveAsync$1(ImportService.java:264)
snowstorm      | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
snowstorm      | 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
snowstorm      | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
snowstorm      | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
snowstorm      | 	at java.base/java.lang.Thread.run(Unknown Source)
snowstorm      | Caused by: java.lang.RuntimeException: es: No address associated with hostname
snowstorm      | 	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.translateException(ElasticsearchRestTemplate.java:365)
snowstorm      | 	... 29 common frames omitted
snowstorm      | Caused by: java.io.IOException: es: No address associated with hostname
snowstorm      | 	at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:884)
snowstorm      | 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:283)
snowstorm      | 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)
snowstorm      | 	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1632)
snowstorm      | 	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1602)
snowstorm      | 	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1572)
snowstorm      | 	at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1088)
snowstorm      | 	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.lambda$searchScrollStart$11(ElasticsearchRestTemplate.java:276)
snowstorm      | 	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.execute(ElasticsearchRestTemplate.java:348)
snowstorm      | 	... 28 common frames omitted
snowstorm      | Caused by: java.net.UnknownHostException: es: No address associated with hostname
snowstorm      | 	at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
snowstorm      | 	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(Unknown Source)
snowstorm      | 	at java.base/java.net.InetAddress.getAddressesFromNameService(Unknown Source)
snowstorm      | 	at java.base/java.net.InetAddress$NameServiceAddresses.get(Unknown Source)
snowstorm      | 	at java.base/java.net.InetAddress.getAllByName0(Unknown Source)
snowstorm      | 	at java.base/java.net.InetAddress.getAllByName(Unknown Source)
snowstorm      | 	at java.base/java.net.InetAddress.getAllByName(Unknown Source)
snowstorm      | 	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
snowstorm      | 	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalAddressResolver.resolveRemoteAddress(PoolingNHttpClientConnectionManager.java:666)
snowstorm      | 	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalAddressResolver.resolveRemoteAddress(PoolingNHttpClientConnectionManager.java:637)
snowstorm      | 	at org.apache.http.nio.pool.AbstractNIOConnPool.processPendingRequest(AbstractNIOConnPool.java:472)
snowstorm      | 	at org.apache.http.nio.pool.AbstractNIOConnPool.lease(AbstractNIOConnPool.java:280)
snowstorm      | 	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.requestConnection(PoolingNHttpClientConnectionManager.java:295)
snowstorm      | 	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.requestConnection(AbstractClientExchangeHandler.java:381)
snowstorm      | 	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.start(DefaultClientExchangeHandlerImpl.java:130)
snowstorm      | 	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.execute(CloseableHttpAsyncClientBase.java:116)
snowstorm      | 	at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:138)
snowstorm      | 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:279)
snowstorm      | 	... 35 common frames omitted
snowstorm      |    
```

**Comment by kaicode** [comment]
Hi @divinebanana,
I'm sorry to hear that Snowstorm is not working for you. Thank you for raising such a clear issue with plenty of context.

I'm Googling about this "No address associated with hostname" Elasticsearch error... 
Can I ask, have you given the Docker container a hostname that contains an underscore? 

.. otherwise I will attempt to reproduce this issue locally.

**Comment by divinebanana** [comment]
We didn't change the `docker compose` configuration on our side. From my discoveries, it feels like the Java error that `snowstorm` has is connected to the fact that `elasticsearch exited with code 137`, hence it is trying to access data which isn't available resulting in `No address associated with hostname` error appears.

**Comment by kaicode** [comment]
The `docker-compose.yml` file has a specific version of the elasticsearch container but it pulls the latest snowstorm container, this has probably moved on to a pre-release version now.
Please edit the docker-compose file to set the snowstorm container version to 9.2.0. That fixed it for me. I also needed to start with a fresh Docker volume.
```
   snowstorm:
    image: snomedinternational/snowstorm:9.2.0
```

**Comment by divinebanana** [comment]
I will pass this to my team members and will get back to you after they test this out. Thank you for the prompt replies.

**Comment by divinebanana** [comment]
Hey @kaicode we were able to make this work. Thank you for the help. Closing the issue.

**Comment by kaicode** [comment]
Great news! Thanks for the update.
