### ISSUE TITLE
Unable to load SNOMED CT into Docker instance

### ISSUE THREAD

**Issue by anthonylevine** [IHTSDO/snowstorm#597]
Hello,

I am having trouble seeding elastic search with the initial data set while running the server via containers. 

I pulled down the repository, and ran the docker compose command and all of the service appeared to start successfully. I was able to hit the Swagger endpoint as while as the browser.

I then used the instructions on this [page](https://github.com/IHTSDO/snowstorm/blob/10.1.0/docs/loading-snomed.md) to create a new import job (which was successful and starts in the "waiting for file" state). It also successfully accepts the upload of the file, but after a few seconds the job goes to "FAILED". I've tried loading both the UK and US editions with no luck. The error I'm receiving is this from the container logs:

![image](https://github.com/IHTSDO/snowstorm/assets/4107984/f616ddf4-eedb-47fb-ad97-5c09a2eecd90)

-unzip7629340547499418411/der2_sssssssRefset_MRCMDomainSnapshot_INT_20240501.txt
2024-05-30 09:56:26 snowstorm      | 2024-05-30T13:56:26.195Z  INFO 1 --- [pool-3-thread-1] o.ihtsdo.otf.snomedboot.ReleaseImporter  : Unzipping file to /tmp/temp-rf2-unzip7629340547499418411/der2_cissccRefset_MRCMAttributeDomainSnapshot_INT_20240501.txt
2024-05-30 09:56:26 snowstorm      | 2024-05-30T13:56:26.196Z  INFO 1 --- [pool-3-thread-1] o.ihtsdo.otf.snomedboot.ReleaseImporter  : Unzipping file to /tmp/temp-rf2-unzip7629340547499418411/der2_ssccRefset_MRCMAttributeRangeSnapshot_INT_20240501.txt
2024-05-30 09:56:26 snowstorm      | 2024-05-30T13:56:26.196Z  INFO 1 --- [pool-3-thread-1] o.ihtsdo.otf.snomedboot.ReleaseImporter  : Unzipping file to /tmp/temp-rf2-unzip7629340547499418411/der2_cRefset_MRCMModuleScopeSnapshot_INT_20240501.txt
2024-05-30 09:56:26 snowstorm      | 2024-05-30T13:56:26.196Z  INFO 1 --- [pool-3-thread-1] o.ihtsdo.otf.snomedboot.ReleaseImporter  : Unzipping file to /tmp/temp-rf2-unzip7629340547499418411/der2_scsRefset_ComponentAnnotationStringValueSnapshot_INT_20240501.txt
2024-05-30 09:56:26 snowstorm      | 2024-05-30T13:56:26.196Z  INFO 1 --- [pool-3-thread-1] o.ihtsdo.otf.snomedboot.ReleaseImporter  : Unzipping file to /tmp/temp-rf2-unzip7629340547499418411/der2_sscsRefset_MemberAnnotationStringValueSnapshot_INT_20240501.txt
2024-05-30 09:56:34 snowstorm      | 2024-05-30T13:56:34.385Z  INFO 1 --- [pool-3-thread-1] o.ihtsdo.otf.snomedboot.ReleaseImporter  : Loading SNAPSHOT release files ReleaseFiles{conceptPaths=[/tmp/temp-rf2-unzip7629340547499418411/sct2_Concept_Snapshot_INT_20240501.txt], descriptionPaths=[/tmp/temp-rf2-unzip7629340547499418411/sct2_Description_Snapshot-en_INT_20240501.txt], textDefinitionPaths=[/tmp/temp-rf2-unzip7629340547499418411/sct2_TextDefinition_Snapshot-en_INT_20240501.txt], relationshipPaths=[/tmp/temp-rf2-unzip7629340547499418411/sct2_Relationship_Snapshot_INT_20240501.txt], concreteRelationshipPaths=[/tmp/temp-rf2-unzip7629340547499418411/sct2_RelationshipConcreteValues_Snapshot_INT_20240501.txt], statedRelationshipPaths=[/tmp/temp-rf2-unzip7629340547499418411/sct2_StatedRelationship_Snapshot_INT_20240501.txt], identifierPaths=[/tmp/temp-rf2-unzip7629340547499418411/sct2_Identifier_Snapshot_INT_20240501.txt], refsetPaths=[/tmp/temp-rf2-unzip7629340547499418411/der2_cRefset_MRCMModuleScopeSnapshot_INT_20240501.txt, /tmp/temp-rf2-unzip7629340547499418411/der2_cRefset_AssociationSnapshot_INT_20240501.txt, /tmp/temp-rf2-unzip7629340547499418411/der2_cRefset_AttributeValueSnapshot_INT_20240501.txt, /tmp/temp-rf2-unzip7629340547499418411/der2_sscsRefset_MemberAnnotationStringValueSnapshot_INT_20240501.txt, /tmp/temp-rf2-unzip7629340547499418411/der2_sRefset_SimpleMapSnapshot_INT_20240501.txt, /tmp/temp-rf2-unzip7629340547499418411/der2_iisssccRefset_ExtendedMapSnapshot_INT_20240501.txt, /tmp/temp-rf2-unzip7629340547499418411/der2_cissccRefset_MRCMAttributeDomainSnapshot_INT_20240501.txt, /tmp/temp-rf2-unzip7629340547499418411/der2_cciRefset_RefsetDescriptorSnapshot_INT_20240501.txt, /tmp/temp-rf2-unzip7629340547499418411/der2_sssssssRefset_MRCMDomainSnapshot_INT_20240501.txt, /tmp/temp-rf2-unzip7629340547499418411/der2_ciRefset_DescriptionTypeSnapshot_INT_20240501.txt, /tmp/temp-rf2-unzip7629340547499418411/sct2_sRefset_OWLExpressionSnapshot_INT_20240501.txt, /tmp/temp-rf2-unzip7629340547499418411/der2_scsRefset_ComponentAnnotationStringValueSnapshot_INT_20240501.txt, /tmp/temp-rf2-unzip7629340547499418411/der2_ssRefset_ModuleDependencySnapshot_INT_20240501.txt, /tmp/temp-rf2-unzip7629340547499418411/der2_ssccRefset_MRCMAttributeRangeSnapshot_INT_20240501.txt, /tmp/temp-rf2-unzip7629340547499418411/der2_Refset_SimpleSnapshot_INT_20240501.txt, /tmp/temp-rf2-unzip7629340547499418411/der2_cRefset_LanguageSnapshot-en_INT_20240501.txt]}
2024-05-30 09:56:34 snowstorm      | 2024-05-30T13:56:34.454Z ERROR 1 --- [pool-3-thread-1] o.s.s.core.rf2.rf2import.ImportService   : Failed RF2 SNAPSHOT import on branch MAIN. ID 3a7ee393-1acf-4b22-b0e4-65039a0f4118
2024-05-30 09:56:34 snowstorm      | 
2024-05-30 09:56:34 snowstorm      | java.lang.IllegalStateException: Branch MAIN is already locked
2024-05-30 09:56:34 snowstorm      |    at io.kaicode.elasticvc.api.BranchService.lockBranch(BranchService.java:359)
2024-05-30 09:56:34 snowstorm      |    at io.kaicode.elasticvc.api.BranchService.lockBranch(BranchService.java:354)
2024-05-30 09:56:34 snowstorm      |    at io.kaicode.elasticvc.api.BranchService.openCommit(BranchService.java:342)
2024-05-30 09:56:34 snowstorm      |    at io.kaicode.elasticvc.api.BranchService.openCommit(BranchService.java:332)
2024-05-30 09:56:34 snowstorm      |    at org.snomed.snowstorm.core.rf2.rf2import.ImportComponentFactoryImpl.loadingComponentsStarting(ImportComponentFactoryImpl.java:210)
2024-05-30 09:56:34 snowstorm      |    at org.ihtsdo.otf.snomedboot.ReleaseImporter$ImportRun.doLoadReleaseFiles(ReleaseImporter.java:232)
2024-05-30 09:56:34 snowstorm      |    at org.ihtsdo.otf.snomedboot.ReleaseImporter$ImportRun.doLoadReleaseFiles(ReleaseImporter.java:203)
2024-05-30 09:56:34 snowstorm      |    at org.ihtsdo.otf.snomedboot.ReleaseImporter.loadSnapshotReleaseFiles(ReleaseImporter.java:46)
2024-05-30 09:56:34 snowstorm      |    at org.ihtsdo.otf.snomedboot.ReleaseImporter.loadSnapshotReleaseFiles(ReleaseImporter.java:80)
2024-05-30 09:56:34 snowstorm      |    at org.snomed.snowstorm.core.rf2.rf2import.ImportService.snapshotImport(ImportService.java:232)
2024-05-30 09:56:34 snowstorm      |    at org.snomed.snowstorm.core.rf2.rf2import.ImportService.importFiles(ImportService.java:179)
2024-05-30 09:56:34 snowstorm      |    at org.snomed.snowstorm.core.rf2.rf2import.ImportService.importArchive(ImportService.java:132)
2024-05-30 09:56:34 snowstorm      |    at org.snomed.snowstorm.core.rf2.rf2import.ImportService.lambda$importArchiveAsync$1(ImportService.java:280)
2024-05-30 09:56:34 snowstorm      |    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2024-05-30 09:56:34 snowstorm      |    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2024-05-30 09:56:34 snowstorm      |    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2024-05-30 09:56:34 snowstorm      |    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2024-05-30 09:56:34 snowstorm      |    at java.base/java.lang.Thread.run(Thread.java:840)
2024-05-30 09:56:34 snowstorm      |

Any help would be greatly appreciated. Thank you. 

To add: I've deleted and repulled the containers a handful of times which doesn't seem to do the trick either.

**Comment by kaicode** [comment]
Sorry to hear that the import did not work for you first time.
This "branch MAIN is already locked" message will happen if the container previously crashed during an import. Please recreate the container with a fresh volume and try the import again. Send us the first error message you get. Then we will try to make further suggestions.

**Comment by anthonylevine** [comment]
Thank you much. That did it. 

I apologize, I had deleted the images and re-pulled and started them a handful of times before reaching out but I didn't remove the corresponding volumes when doing that.

**Comment by kaicode** [comment]
No need to apologize! I'm pleased to hear you solved it 👍
