### ISSUE TITLE
Importing RF2 results in java heap error

### ISSUE THREAD

**Issue by rowanvb** [IHTSDO/snowstorm#79]
```
2019-10-17 14:25:01.775  INFO 1 --- [pool-2-thread-1] i.k.elasticvc.api.ComponentService       : Saving batch of 3082 QueryConcepts
2019-10-17 14:25:02.162  INFO 1 --- [pool-2-thread-1] o.snomed.snowstorm.core.util.TimerUtil   : Timer TC index stated: Save updated QueryConcepts took 279.815 seconds
2019-10-17 14:25:02.163  INFO 1 --- [pool-2-thread-1] o.snomed.snowstorm.core.util.TimerUtil   : Timer TC index stated: total took 404.48 seconds
2019-10-17 14:25:29.589  INFO 1 --- [pool-2-thread-1] o.snomed.snowstorm.core.util.TimerUtil   : Timer TC index inferred: Collect changed is-a relationships. took 27.426 seconds
2019-10-17 14:25:32.617  INFO 1 --- [pool-2-thread-1] o.s.s.c.d.s.SemanticIndexUpdateService   : Performing incremental update of inferred semantic index
2019-10-17 14:25:33.078  INFO 1 --- [pool-2-thread-1] o.snomed.snowstorm.core.util.TimerUtil   : Timer TC index inferred: Collect existingAncestors from QueryConcept. took 3.489 seconds
2019-10-17 14:25:33.956  INFO 1 --- [pool-2-thread-1] o.s.s.c.d.s.SemanticIndexUpdateService   : 0 existing nodes loaded.
2019-10-17 14:30:46.290  INFO 1 --- [pool-2-thread-1] o.snomed.snowstorm.core.util.TimerUtil   : Timer TC index inferred: Update graph using relationships of concepts with changed modelling. took 312.334 seconds
2019-10-17 14:30:48.297  INFO 1 --- [pool-2-thread-1] o.snomed.snowstorm.core.util.TimerUtil   : Timer TC index inferred: Collect existingDescendants from QueryConcept. took 2.007 seconds
Exception in thread "http-nio-8080-Acceptor-0" java.lang.OutOfMemoryError: Java heap space
        at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
        at java.nio.ByteBuffer.allocate(ByteBuffer.java:335)
        at org.apache.tomcat.util.net.SocketBufferHandler.<init>(SocketBufferHandler.java:41)
        at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:404)
```

I have been trying to import the SnomedCT_Netherlands_EditionRelease_PRODUCTION_20190930T120000Z.zip following the import guide on an AWS instance. 
I am limiting the resources available for the pod to 800m CPU and 6g RAM. Besides that, I have tried to set the -Xmx to 4g, but this does not seem to have an effect. Also tried using the XX:+UseContainerSupport, but this has no effect either (not sure if the java image supports this flag?). Checking the pod resource usage, it seems like the pod doesn't use more than 1.5g RAM. 

Do you have any suggestions what else I could try? It might be that there is some memory leak in the end of this import process, but I am not really sure..

**Comment by rorydavidson** [comment]
Have you had a look at the thread here - https://github.com/IHTSDO/snowstorm/issues/74 - that may help?

**Comment by kaicode** [comment]
Hi @rowanvb, thanks for reaching out to us.

The JVM running Snowstorm is running out of memory. The last part of the import commit builds the semantic index which is used to answer ECL queries, this takes quite a bit of memory to build.
The JVM will need more memory for this process to complete. Please include the following flags when starting Snowstorm: 
```java -Xms4g -Xmx4g```
**Xmx** limits the maximum heap size but it does not guarantee that the JVM can get enough memory.
**Xms** sets the minimum heap size, if the JVM can not claim this amount of memory it will fail to start.

You may be able to get away with slightly less memory than 4g depending on your use case. You could alternatively use a larger machine to run the import and build the Elasticsearch indices and then run a low memory instance of Snowstorm for light usage using the prebuilt data.

I hope that helps!

Kind regards,
Kai

**Comment by rowanvb** [comment]
Thanks, this worked indeed. I had to upgrade our nodes to have 8g ram, and that resolved all issues
