### ISSUE TITLE
Possible ElasticSearch problem?

### ISSUE THREAD

**Issue by lihaiming** [IHTSDO/snowstorm#86]
we use ElasticSearch 6.4.0 and changed the POM file accordingly and build to snowstorm-4.4.0.jar.

running 
####
java -Xdebug -Xms2g -Xmx4g -jar /data/store/snowstorm/snowstorm.jar --delete-indices --import=/data/store/snomed/SnomedCT_InternationalRF2_PRODUCTION_20190731T120000Z.zip --exit
####
add got below error.

what could be the prossible reasons?

####
2019-11-20 13:38:23.616  WARN 25414 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'classificationController': Unsatisfied dependency expressed through field 'classificationService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'classificationService': Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: org.elasticsearch.common.xcontent.XContent.createParser(Lorg/elasticsearch/common/xcontent/NamedXContentRegistry;Ljava/io/InputStream;)Lorg/elasticsearch/common/xcontent/XContentParser;
2019-11-20 13:38:23.628  INFO 25414 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2019-11-20 13:38:23.648  INFO 25414 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-11-20 13:38:23.653 ERROR 25414 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'classificationController': Unsatisfied dependency expressed through field 'classificationService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'classificationService': Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: org.elasticsearch.common.xcontent.XContent.createParser(Lorg/elasticsearch/common/xcontent/NamedXContentRegistry;Ljava/io/InputStream;)Lorg/elasticsearch/common/xcontent/XContentParser;
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:587)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:91)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:373)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1344)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:578)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243)
	at org.snomed.snowstorm.SnowstormApplication.main(SnowstormApplication.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'classificationService': Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: org.elasticsearch.common.xcontent.XContent.createParser(Lorg/elasticsearch/common/xcontent/NamedXContentRegistry;Ljava/io/InputStream;)Lorg/elasticsearch/common/xcontent/XContentParser;
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:138)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:422)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1694)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:579)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1065)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:584)
	... 27 common frames omitted
Caused by: java.lang.NoSuchMethodError: org.elasticsearch.common.xcontent.XContent.createParser(Lorg/elasticsearch/common/xcontent/NamedXContentRegistry;Ljava/io/InputStream;)Lorg/elasticsearch/common/xcontent/XContentParser;
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:557)
	at org.elasticsearch.client.RestHighLevelClient.lambda$performRequestAndParseEntity$2(RestHighLevelClient.java:414)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:445)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:414)
	at org.springframework.data.elasticsearch.rest.ESRestHighLevelClient.performRequestAndParseEntity(ESRestHighLevelClient.java:47)
	at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:355)
	at org.springframework.data.elasticsearch.rest.ElasticsearchRestClient.doExecute(ElasticsearchRestClient.java:214)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:407)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:396)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:46)
	at org.springframework.data.elasticsearch.core.ElasticsearchTemplate.doScroll(ElasticsearchTemplate.java:860)
	at org.springframework.data.elasticsearch.core.ElasticsearchTemplate.startScroll(ElasticsearchTemplate.java:874)
	at org.springframework.data.elasticsearch.core.ElasticsearchTemplate.stream(ElasticsearchTemplate.java:367)
	at org.springframework.data.elasticsearch.core.ElasticsearchTemplate.stream(ElasticsearchTemplate.java:361)
	at org.snomed.snowstorm.core.data.services.classification.ClassificationService.init(ClassificationService.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:365)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:308)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:135)
	... 39 common frames omitted

**Comment by lihaiming** [comment]
is it because i changed elasticsearch.version to 6.4.0 from 6.0.1?

###
		
		<elasticvc.version>2.6.2</elasticvc.version>
		<elasticsearch.version>6.0.1</elasticsearch.version>
###

		<elasticsearch.version>6.4.0</elasticsearch.version>

**Comment by kaicode** [comment]
Hi @lihaiming, there is no need to change the elasticsearch client version in the Snowstorm pom file in order to use Elasticsearch 6.4.0. The Elasticsearch client version 6.0.1 is compatible with any 6.x version of Elasticsearch. We are using Snowstorm in production with one cluster on Elasticsearch 6.5.4 and another cluster on Elasticsearch 6.8.0. Both are using the same version of Snowstorm which has the client library version 6.0.1.

The exception you have includes "NoSuchMethodError" which indicates that the library version you picked is not compatible with one of the other libraries in use such as Spring Data Elasticsearch.

I have not tried upgrading the client version like this so I'm not sure what issues you would encounter. I can recommend using Snowstorm as is. You can not connect to Elasticsearch 7.x but and 6.x version will be okay.

I hope that helps,
Kai

**Comment by lihaiming** [comment]
@kaicode 
Thanks for your clarification. Then what is the purpose of this line in the pom file:

	<elasticsearch.version>6.0.1</elasticsearch.version>

**Comment by kaicode** [comment]
Yes, that line pulls in the correct version of the Elasticsearch Client which the ElasticVC and Spring Boot Elasticsearch libraries require. It shows which Elasticsearch Client we are using but it can not be used to change the version we are using without also updating the other libraries. 

We could exclude this dependency because it's probably a transitive dependency which would be pulled in from ElasticVC but on the other hand it's useful to have it there for visibility. In a perfect world you would be able to change it and everything would work but it looks like there are breaking changes within the library in 6.4.x versions which prevent a smooth upgrade.

I've added comments in the pom in the develop branch to add some clarification. Thanks for pointing out in insufficient naming! 😄
